package gov.saip.applicationservice.common.dto.notifications;

public enum NotificationTemplateCode {
    TRADEMARK_RENEWAL_DUE_PERIOD_STARTED,
    TRADEMARK_RENEWAL_GRACE_PERIOD_STARTED,
    TRADEMARK_RENEWAL_APPLICATION_DESERTION,

    INDUSTRIAL_DESIGN_RENEWAL_DUE_PERIOD_STARTED,
    INDUSTRIAL_DESIGN_RENEWAL_GRACE_PERIOD_STARTED,
    INDUSTRIAL_DESIGN_RENEWAL_APPLICATION_DESERTION,


    PATENT_RENEWAL_DUE_PERIOD_STARTED,
    PATENT_RENEWAL_GRACE_PERIOD_STARTED,
    PATENT_RENEWAL_APPLICATION_DESERTION,

    RE_GENERATE_BILL_NUMBER,PATENT_PRIORITY,PATENT_PAY_BEFORE_COMPLETE,

    DEPOSIT_CERTIFICATE,
    TRADEMARK_APPLICATION_EDIT_NAME_ADDRESS_REPLY_TO_APPLICANT,
    REVOKE_VOLUNTARY_REPLY_TO_APPLICANT,
    TM_AGENCY_REPLY_TO_APPLICANT,

    TRADEMARK_RENEWED,
    TRADEMARK_CHANGE_OWNERSHIP_REPLY_TO_APPLICANT,
    TRADEMARK_EXACT_COPY,
    RESPONSE_TO_THE_REQUEST_OF_REVOKE_PRODUCTS,
    OWNER_OPPOSITION_REPLY_WITHOUT_HEARING_SESSION,
    OWNER_OPPOSITION_REPLY_WITH_HEARING_SESSION,
    OPPOSITION_INTERNAL_ADD_HEARING_SESSION_FOR_OPPOSITION_APPLICANT_TO_OPPOSITION_APPLICANT,
    OPPOSITION_INTERNAL_ADD_HEARING_SESSION_FOR_OPPOSITION_APPLICANT_TO_OWNER,
    OPPOSITION_INTERNAL_ADD_HEARING_SESSION_FOR_OWNER_TO_OWNER,
    OPPOSITION_INTERNAL_ADD_HEARING_SESSION_FOR_OWNER_TO_OPPOSITION_APPLICANT

}
