--liquibase formatted sql
-- changeset application-service:add_saip_code.sql


-- ALTER TABLE application.lk_applicant_category
--     ADD saip_code  varchar(255);
--
-- ALTER TABLE application.lk_application_category
--     ADD saip_code  varchar(255);
--
-- ALTER TABLE application.lk_request_type
--     ADD saip_code  varchar(255);

update application.lk_applicant_category set saip_code = 'NATURAL_PERSON_WITH_NATIONALITY' where id = 1;
update application.lk_applicant_category set saip_code = 'CORPORATION_WITH_NATIONALITY' where id = 2;
update application.lk_applicant_category set saip_code = 'NATURAL_PERSON_WITH_FOREIGN_NATIONALITY' where id = 3;
update application.lk_applicant_category set saip_code = 'FOREIGN_CORPORATION' where id = 4;


update application.lk_application_category set saip_code = 'PATENT' where id = 1;
update application.lk_application_category set saip_code = 'INDUSTRIAL_DESIGN' where id = 2;
update application.lk_application_category set saip_code = 'PLANT_VARIETIES' where id = 3;
update application.lk_application_category set saip_code = 'INTEGRATED_CIRCUITS' where id = 4;
update application.lk_application_category set saip_code = 'TRADEMARK' where id = 5;
update application.lk_application_category set saip_code = 'COPYRIGHT' where id = 6;
update application.lk_application_category set saip_code = 'GEOGRAPHICAL_INDICATION' where id = 7;
update application.lk_application_category set saip_code = 'PUBLICATION' where id = 8;
update application.lk_application_category set saip_code = 'CASE_AND_COMPLAIN' where id = 9;
update application.lk_application_category set saip_code = 'LICENSE' where id = 10;

update application.lk_request_type set saip_code = 'FILE_NEW_APPLICATION' where id = 1;
update application.lk_request_type set saip_code = 'UPDATE_APPLICATION' where id = 2;
update application.lk_request_type set saip_code = 'CHANGE_OWNER_REQUEST' where id = 3;
update application.lk_request_type set saip_code = 'REQUEST__COPY_OF_PATENT' where id = 4;
update application.lk_request_type set saip_code = 'CHANGE_AGENT_REQUEST' where id = 5;
update application.lk_request_type set saip_code = 'ANNUAL_YEAR_FEE' where id = 6;
update application.lk_request_type set saip_code = 'GRANTS_FEE' where id = 7;
update application.lk_request_type set saip_code = 'PUBLICATION_FEE' where id = 8;
update application.lk_request_type set saip_code = 'AGENT_REGISTRATION_REQUEST' where id = 9;
update application.lk_request_type set saip_code = 'SUBSTANSIVE_EXAMINATION_FEE' where id = 10;
update application.lk_request_type set saip_code = '1ST_YEAR' where id = 30;
update application.lk_request_type set saip_code = '2ND_YEAR' where id = 31;
update application.lk_request_type set saip_code = '3RD_YEAR' where id = 32;
update application.lk_request_type set saip_code = '4TH_YEAR' where id = 33;
update application.lk_request_type set saip_code = '5TH_YEAR' where id = 34;
update application.lk_request_type set saip_code = '6TH_YEAR' where id = 35;
update application.lk_request_type set saip_code = '7TH_YEAR' where id = 36;
update application.lk_request_type set saip_code = '8TH_YEAR' where id = 37;
update application.lk_request_type set saip_code = '9TH_YEAR' where id = 38;
update application.lk_request_type set saip_code = '10TH_YEAR' where id = 39;
update application.lk_request_type set saip_code = '11TH_YEAR' where id = 40;
update application.lk_request_type set saip_code = '12TH_YEAR' where id = 41;
update application.lk_request_type set saip_code = '13TH_YEAR' where id = 42;
update application.lk_request_type set saip_code = '14TH_YEAR' where id = 43;
update application.lk_request_type set saip_code = '15TH_YEAR' where id = 44;
update application.lk_request_type set saip_code = '16TH_YEAR' where id = 45;
update application.lk_request_type set saip_code = '17TH_YEAR' where id = 46;
update application.lk_request_type set saip_code = '18TH_YEAR' where id = 47;
update application.lk_request_type set saip_code = '19TH_YEAR' where id = 48;
update application.lk_request_type set saip_code = '20TH_YEAR' where id = 49;
update application.lk_request_type set saip_code = '21ST_YEAR' where id = 50;
update application.lk_request_type set saip_code = 'FILE_NEW_APPLICATION_WITHOUT_PRIORITY' where id = 51;
update application.lk_request_type set saip_code = 'BILL_UPLOAD_FAIL' where id = 52;
update application.lk_request_type set saip_code = 'SUBSTANSIVE_EXAMINATION_APPLICATION_UPDATE' where id = 53;
update application.lk_request_type set saip_code = 'FORM_22_REPLY_APPLICATION_UPDATE' where id = 54;
update application.lk_request_type set saip_code = 'ANNUAL_FEE_ADVANCE' where id = 55;
update application.lk_request_type set saip_code = 'NOTIFY_TO_EXAMINER(SYSTEM_NOTIFICATION)' where id = 56;
update application.lk_request_type set saip_code = 'OBJECTION_SENT_BY_FORMAL_EXAMINER' where id = 57;
update application.lk_request_type set saip_code = 'REJECTION_BY_FORMAL_EXAMINER' where id = 58;
update application.lk_request_type set saip_code = 'GRANT_REPORT_SENT_TO_APPLICANT' where id = 59;
update application.lk_request_type set saip_code = 'FORM_122_REQUEST' where id = 60;
update application.lk_request_type set saip_code = 'FORM_104_REQUEST' where id = 61;
update application.lk_request_type set saip_code = 'INTERNATIONAL_SEARCH_REPORT_REQUEST' where id = 62;
update application.lk_request_type set saip_code = 'LAPSE_REPORT' where id = 63;
update application.lk_request_type set saip_code = 'ÇÁÑÏ_ÚÁÌ_ÊÞÑÍÑ_ÝÍÕ_ÃÆÖÆÚÍ_ÃÚ_ÇÁÇÚÊÑÇÖ' where id = 64;
update application.lk_request_type set saip_code = 'REJECTION_FROM_SUB._EXAMINER' where id = 65;
update application.lk_request_type set saip_code = 'CERTIFICATE_NOTIFICATION' where id = 66;
update application.lk_request_type set saip_code = 'UPDATE_APPLICANT_REQUEST' where id = 67;
update application.lk_request_type set saip_code = 'NEW_AGENT_REQUEST' where id = 68;
update application.lk_request_type set saip_code = 'UPDATE_AGENT_REQUEST' where id = 69;
update application.lk_request_type set saip_code = 'UPDATE_APPLICANTION_INVENTOR' where id = 70;
update application.lk_request_type set saip_code = 'ADD_APPLICANT_TO_APPLICATION' where id = 71;
update application.lk_request_type set saip_code = 'DELETE_APPLICANT_FROM_APPLICATION' where id = 72;
update application.lk_request_type set saip_code = 'ADD_INVENTOR_TO_APPLICATION' where id = 73;
update application.lk_request_type set saip_code = 'DELETE_INVENTOR_FROM_APPLICATION' where id = 74;
update application.lk_request_type set saip_code = 'PAYEMNT_RECIEVED' where id = 76;
update application.lk_request_type set saip_code = 'WITHDRAW_APPLICATION' where id = 77;
update application.lk_request_type set saip_code = 'FORGOT_PASSWORD' where id = 78;
update application.lk_request_type set saip_code = 'CHANGE_PASSWORD' where id = 79;
update application.lk_request_type set saip_code = 'APPLICANT_REGISTER' where id = 80;
update application.lk_request_type set saip_code = 'REQUEST__COPY_OF_CERTIFICATE' where id = 82;
update application.lk_request_type set saip_code = 'UPDATE_APPLICATION_APPLICANT' where id = 83;
update application.lk_request_type set saip_code = 'UPDATE_PERSONAL_INFO' where id = 84;
update application.lk_request_type set saip_code = 'REJECT_SERVICE_REQUEST' where id = 85;
update application.lk_request_type set saip_code = 'UPDATE_PRIORITY_DOCUMENT' where id = 86;
update application.lk_request_type set saip_code = 'UPDATE_AGENT_TAWKEEL_DOC' where id = 87;
update application.lk_request_type set saip_code = 'UPDATE_INVENTOR_TANAZUL_DOC' where id = 88;
update application.lk_request_type set saip_code = 'FORGOTUSERNAME' where id = 89;
update application.lk_request_type set saip_code = 'FORMAL_OBJECTION_REPLY_WITH_UPDATE' where id = 90;
update application.lk_request_type set saip_code = 'PROVIDEPRIORITYDOCUMENTREMINDER' where id = 91;
update application.lk_request_type set saip_code = 'ADD_APPLICATION_AGENT_REQUEST' where id = 92;
update application.lk_request_type set saip_code = 'CANCEL_APPLICATION_AGENT_REQUEST' where id = 93;
update application.lk_request_type set saip_code = 'CHANGE_SERVICE_REQUEST_EXAMINER' where id = 94;
update application.lk_request_type set saip_code = '23RD_YEAR' where id = 95;
update application.lk_request_type set saip_code = '22ND_YEAR' where id = 96;
update application.lk_request_type set saip_code = '24TH_YEAR' where id = 97;
update application.lk_request_type set saip_code = '25TH_YEAR' where id = 98;
update application.lk_request_type set saip_code = 'UPDATE_DRAWING__FROM_FORMAL' where id = 99;
update application.lk_request_type set saip_code = 'FORMAL_EXAMINATION_REPLY_WITHOUT_UPDATE' where id = 100;
update application.lk_request_type set saip_code = 'ISSUE_CERTIFICATE' where id = 101;
update application.lk_request_type set saip_code = 'EXTEND_PERIOD_FORMAL_EXAMINATION' where id = 102;
update application.lk_request_type set saip_code = 'ADD_APPLICATION_PRIORITY' where id = 103;
update application.lk_request_type set saip_code = 'EDIT_APPLICATION_REQUEST_FOR_AST_EXAMINER' where id = 106;
update application.lk_request_type set saip_code = 'CANCELING_SERVICE_REQUEST' where id = 107;
update application.lk_request_type set saip_code = 'UPDATE_DOCUMENT_FROM_ASST_EXAMINER' where id = 109;
update application.lk_request_type set saip_code = 'ISSUE_CERTIFICATE_TO_AGENT' where id = 110;
update application.lk_request_type set saip_code = 'APPLICANTNAMEUPDATE_BY_GRANTMANAGER' where id = 111;
update application.lk_request_type set saip_code = 'AUTHORIZE_CONTRACT_REGISTRATION' where id = 112;
update application.lk_request_type set saip_code = 'CERTFICATE_TITLE_UPDATE_BY_GRANT_MANAGER' where id = 113;
update application.lk_request_type set saip_code = 'PRIORITY_UPDATE_BY_GRANT_MANAGER' where id = 114;
update application.lk_request_type set saip_code = 'INVENTOR_UPDATE_BY_GRANT_MANAGER' where id = 115;
update application.lk_request_type set saip_code = 'UPDATE_APPLICANT_NAME' where id = 116;
update application.lk_request_type set saip_code = 'CANCEL_APPLICATION_CERTIFICATE' where id = 117;
update application.lk_request_type set saip_code = 'REISSUANCE_OF_CERTIFICATE' where id = 118;
update application.lk_request_type set saip_code = 'REMINDER_NOTIFICATION' where id = 119;
update application.lk_request_type set saip_code = 'FORM_104_RETURNED_WITHOUT_DOCUMENTS' where id = 120;
update application.lk_request_type set saip_code = 'ISR_RETURNED_WITHOUT_DOCUMENTS' where id = 121;
update application.lk_request_type set saip_code = 'FORM-22_RETURNED_WITHOUT_DOCUMENTS' where id = 122;
update application.lk_request_type set saip_code = 'DELEGATE_CONTROL' where id = 123;
update application.lk_request_type set saip_code = 'TITLE_UPDATE_BY_EXAMINER' where id = 124;
update application.lk_request_type set saip_code = 'UPDATE_AGENT_TAWKEEL_DOC_FROM_INTERNAL' where id = 125;
update application.lk_request_type set saip_code = 'UPDATECLASSIFICATIONFROMINTERNAL' where id = 126;
update application.lk_request_type set saip_code = 'ADD_LEGAL_DOCUMENT_FROM_INTERNAL' where id = 127;
update application.lk_request_type set saip_code = 'PUBLISHING_DOCUMENT' where id = 128;
update application.lk_request_type set saip_code = 'DELETE_INVENTO_FROM_INTERNAL' where id = 129;
update application.lk_request_type set saip_code = 'ADDSECONDARYAPPLICANTFROMINTERNAL' where id = 130;
update application.lk_request_type set saip_code = 'ADD_APPLICATION_INVENTOR_FROM_INTERNAL' where id = 131;
update application.lk_request_type set saip_code = 'SECONDARYAPPLICANTDELETEDBYDEPT' where id = 132;
update application.lk_request_type set saip_code = 'SUBSTANTIVEREPLYWITHOUTUPDATE' where id = 133;
update application.lk_request_type set saip_code = 'REPORTFORMSREMINDERNOTIFICATION' where id = 134;
update application.lk_request_type set saip_code = 'EXTEND_SUB_REPLY_PERIOD' where id = 135;
update application.lk_request_type set saip_code = 'UPDATEPCTINFO' where id = 136;
update application.lk_request_type set saip_code = 'RE_ACTIVATION_REQUEST_BY_USER' where id = 137;
update application.lk_request_type set saip_code = 'DELETE_PRIORITY_BY_INTERNAL_USER' where id = 138;
update application.lk_request_type set saip_code = 'AGREEMENT_AT_LOGIN_OLD' where id = 139;
update application.lk_request_type set saip_code = 'AGREEMENT_AT_LOGIN' where id = 140;
update application.lk_request_type set saip_code = 'ADD_ACCERLATED_EXAMINATION' where id = 309;
update application.lk_request_type set saip_code = 'ADD_FAST_TRACK_EXAMINATION' where id = 310;
update application.lk_request_type set saip_code = 'ADD_PPH_EXAMINATION' where id = 311;