--liquibase formatted sql
-- changeset application-service:lk_application_status.sql

INSERT INTO application.lk_application_status (id, ips_status_desc_ar, ips_status_desc_en, is_deleted)
VALUES (1, N'طلب جديد', N'New Application', 0),
       (2, N'فحص شكلي', N'Formal examination', 0),
       (3, N'فحص موضوعي', N'Substantive examination', 0),
       (4, N'مُنح وثيقة حماية', N'Granted', 0),
       (5, N'مرفوض', N'Rejected', 0),
       (6, N'ساقط', N'Lapsed', 0),
       (7, N'مسحوب', N'Withdrawn', 0),
       (8, N'اعداد وثيقة الحماية', N'Preparation of protection document', 0),
       (9, N'إنتظار الفحص الشكلي', N'waiting for Formal examination', 0),
       (10, N'إنتظار الفحص الموضوعي', N'waiting for Substantive examination', 0),
       (11, N'إنتظار أعداد وثيقة حماية', N'wating for Preparation of protection document', 0),
       (12, N'انتظار دفع رسوم التعديل على الطلب', N'Waiting for Formal Examination Fee', 0),
       (13, N'انتظار دفع تكاليف الفحص الموضوعي والنشر', N'Waiting for Publication & Substansive Payemnt', 0),
       (14, N'تقرير فحص شكلي', N'Objection Raised from Formal Examination', 0),
       (15, N'انتظار دفع رسوم المنح', N'Waiting for Grant Payment', 0),
       (16, N'الطلب تحت الفحص', N'Application under Process', 0),
       (17, N'فواتير معلقة', N'Pay Pending Bill', 0),
       (18, N'تقرير فحص موضوعي', N'Objection Raised from Substansive Examiner', 0),
       (19, N'تقرير طلب مسنتدات إضافية', N'Search Report Form Request', 0),
       (20, N'انتظار مستند الاسبقية', N'Update Priority Information', 0),
       (21, N'تم ايداع الطلب', N'Application Recieved', 0),
       (22, N'إنتهاء مدة الحماية', N'Protection Period Finished', 0),
       (23, N'طلب عناصر حماية بديلة', N'Waiting for Form 22 reply', 0),
       (24, N'طلب دراسات لمسحضرات عشبية', N'Waiting for Form 104 reply', 0),
       (25, N'إنتهاء مدة الحماية', N'Expired', 0),
       (26, N'براءة ملغاة', N'Canceled', 0),
       (27, N'الغاء وثيقة الحماية', N'Cancel Certificate', 0),
       (28, N'تقرير فحص موضوعي-2', N'Objection Raised from Substansive Examiner', 0),
       (29, N'معلق', N'Suspended', 0),
       (30, N'مبطل', 'Invalidated', 0),
       (31, N'غير مكتمل', 'Incomplete', 0);