INSERT INTO application.lk_document_type (id, name, code, name_ar, description, category, doc_order, is_deleted) VALUES (69, N'Grievance Statement', N'Grievance Statement', N'بيان التظلم', N'بيان التظلم', N'GRIEVANCE', NULL,0);
INSERT INTO application.lk_document_type (id, name, code, name_ar, description, category, doc_order, is_deleted) VALUES (70, N'Grievance POA', N'Grievance POA', N'وثيقة التفويض', N'وثيقة التفويض', N'GRIEVANCE', NULL,0);
INSERT INTO application.lk_document_type (id, name, code, name_ar, description, category, doc_order, is_deleted) VALUES (71, N'Comments For Formal Examiner', N'Comments For Formal Examiner', N'اضافة تعليقات للفاحص الشكلي', N'اضافة تعليقات للفاحص الشكلي', N'GRIEVANCE', NULL,0);
INSERT INTO application.lk_document_type (id, name, code, name_ar, description, category, doc_order, is_deleted) VALUES (72, N'Grievance Committee Decisions ', N'Grievance Committee Decisions', N'قرارات لجنة التظلم', N'قرارات لجنة التظلم', N'GRIEVANCE', NULL,0);

INSERT INTO application.lk_document_type (id, name, code, name_ar, description, category, doc_order, is_deleted) VALUES (73, N'Licensing Contract', N'Licensing Contract', N'عقد الترخيص', N'عقد الترخيص', N'LICENSING', NULL,0);
INSERT INTO application.lk_document_type (id, name, code, name_ar, description, category, doc_order, is_deleted) VALUES (75, N'Licensing POA', N'Licensing POA', N'وثيقة التفويض', N'وثيقة التفويض', N'LICENSING', NULL,0);
INSERT INTO application.lk_document_type (id, name, code, name_ar, description, category, doc_order, is_deleted) VALUES (76, N'Licensing Eligibility', N'Licensing Eligibility', N'احقية الترخيص', N'احقية الترخيص', N'LICENSING', NULL,0);
INSERT INTO application.lk_document_type (id, name, code, name_ar, description, category, doc_order, is_deleted) VALUES (77, N'Modified Licensing Contract', N'Modified Licensing Contract', N'عقد الترخيص المعدل', N'عقد الترخيص المعدل', N'LICENSING', NULL,0);
INSERT INTO application.lk_document_type (id, name, code, name_ar, description, category, doc_order, is_deleted) VALUES (78, N'Proof Of Compulsory License Eligibility', N'Proof Of Compulsory License Eligibility', N'اثبات احقية الترخيص الاجباري', N'اثبات احقية الترخيص الاجباري', N'LICENSING', NULL,0);
INSERT INTO application.lk_document_type (id, name, code, name_ar, description, category, doc_order, is_deleted) VALUES (79, N'Proof Of Cancellation Or Expiry Of The License Contract', N'Proof Of Cancellation Or Expiry Of The License Contract', N'اثبات الغاء او انتهاء عقد الترخيص', N'اثبات الغاء او انتهاء عقد الترخيص', N'LICENSING', NULL,0);


INSERT INTO application.lk_document_type (id, name, code, name_ar, description, category, doc_order, is_deleted) VALUES (80, N'Support Document', N'Support Document', N'وثيقة الدعم', N'وثيقد الدعم', N'PROTECTION PERIOD EXTENSION REQUEST', NULL,0);
INSERT INTO application.lk_document_type (id, name, code, name_ar, description, category, doc_order, is_deleted) VALUES (81, N'Protection Period Extension Request POA', N'Protection Period Extension Request POA', N'وثيقة التفويض', N'وثيقة التفويض', N'PROTECTION PERIOD EXTENSION REQUEST', NULL,0);
INSERT INTO application.lk_document_type (id, name, code, name_ar, description, category, doc_order, is_deleted) VALUES (82, N'Assignment deed document', N'Assignment deed document', N',وثيقة سند التنازل', N'وثيقة سند التنازل', N'PROTECTION PERIOD EXTENSION REQUEST', NULL,0);
