INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'في حالة وجود رسومات توضيحية تخص الطلب يجب أن يستخدم قالب الوصف الكامل الذي يحتوي على عنوان شرح مختصر للرسومات وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب أن يحتوي الوصف الكامل على " خلفية الاختراع , الوصف العام للاختراع , شرح مختصر للرسومات (إن وجدت) , الوصف التفصيلي" وتكون مرتبة في بداية الصفحة ويوضع تحتها خط وذلك طبقاً لأحكام المادة الرابعة عشرة من اللائحة التنفيذية', true, 'يجب أن يحتوي الوصف الكامل على " خلفية الاختراع , الوصف العام للاختراع , شرح مختصر للرسومات (إن وجدت) , الوصف التفصيلي" وتكون مرتبة في بداية الصفحة ويوضع تحتها خط وذلك طبقاً لأحكام المادة الرابعة عشرة من اللائحة التنفيذية', 'يجب أن يحتوي الوصف الكامل على " خلفية الاختراع , الوصف العام للاختراع , شرح مختصر للرسومات (إن وجدت) , الوصف التفصيلي" وتكون مرتبة في بداية الصفحة ويوضع تحتها خط وذلك طبقاً لأحكام المادة الرابعة عشرة من اللائحة التنفيذية', 3, 4, NULL, 3, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'الوصف الكامل لم يتضمن "خلفية الاختراع" وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الأولى من اللائحة التنفيذية', 'الوصف الكامل لم يتضمن "خلفية الاختراع" وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الأولى من اللائحة التنفيذية', true, 'الوصف الكامل لم يتضمن "خلفية الاختراع" وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الأولى من اللائحة التنفيذية', 'الوصف الكامل لم يتضمن "خلفية الاختراع" وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الأولى من اللائحة التنفيذية', 1, 4, NULL, 3, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'الوصف الكامل لم يتضمن "الوصف العام للاختراع" وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الثانية من اللائحة التنفيذية', 'الوصف الكامل لم يتضمن "الوصف العام للاختراع" وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الثانية من اللائحة التنفيذية', true, 'الوصف الكامل لم يتضمن "الوصف العام للاختراع" وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الثانية من اللائحة التنفيذية', 'الوصف الكامل لم يتضمن "الوصف العام للاختراع" وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الثانية من اللائحة التنفيذية', 1, 4, NULL, 3, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'الوصف الكامل لم يتضمن "الوصف التفصيلي" وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الرابعة من اللائحة التنفيذية', 'الوصف الكامل لم يتضمن "الوصف التفصيلي" وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الرابعة من اللائحة التنفيذية', true, 'الوصف الكامل لم يتضمن "الوصف التفصيلي" وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الرابعة من اللائحة التنفيذية', 'الوصف الكامل لم يتضمن "الوصف التفصيلي" وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الرابعة من اللائحة التنفيذية', 1, 4, NULL, 3, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'الوصف الكامل لم يتضمن "شرح مختصر للرسومات" وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الثالثة من اللائحة التنفيذية', 'الوصف الكامل لم يتضمن "شرح مختصر للرسومات" وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الثالثة من اللائحة التنفيذية', true, 'الوصف الكامل لم يتضمن "شرح مختصر للرسومات" وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الثالثة من اللائحة التنفيذية', 'الوصف الكامل لم يتضمن "شرح مختصر للرسومات" وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الثالثة من اللائحة التنفيذية', 1, 4, NULL, 3, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب تعبئة القالب بالطريقة الصحيحة في (أدخل العنوان باللغة العربية) وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية للنظام', 'يجب تعبئة القالب بالطريقة الصحيحة في (أدخل العنوان باللغة العربية) وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية للنظام', true, 'يجب تعبئة القالب بالطريقة الصحيحة في (أدخل العنوان باللغة العربية) وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية للنظام', 'يجب تعبئة القالب بالطريقة الصحيحة في (أدخل العنوان باللغة العربية) وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية للنظام', 1, 4, NULL, 3, 'APPLICANT', NULL, 'FORMAL_EXAMINER');


