
-----------------------اسم الاختراع--------------------

INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن تكون ترجمة اسم الاختراع صحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب أن تكون ترجمة اسم الاختراع صحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', true, 'يجب أن تكون ترجمة اسم الاختراع صحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب أن تكون ترجمة اسم الاختراع صحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 1, 3, NULL, 1, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب تصحيح الأخطاء الإملائية في اسم الاختراع (عربي/إنجليزي) وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب تصحيح الأخطاء الإملائية في اسم الاختراع (عربي/إنجليزي) وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', true, 'يجب تصحيح الأخطاء الإملائية في اسم الاختراع (عربي/إنجليزي) وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب تصحيح الأخطاء الإملائية في اسم الاختراع (عربي/إنجليزي) وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 1, 3, NULL, 1, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن يتطابق اسم الاختراع في نموذج التقديم كما هو في التنازل وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية للنظام', 'يجب أن يتطابق اسم الاختراع في نموذج التقديم كما هو في التنازل وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية للنظام', true, 'يجب أن يتطابق اسم الاختراع في نموذج التقديم كما هو في التنازل وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية للنظام', 'يجب أن يتطابق اسم الاختراع في نموذج التقديم كما هو في التنازل وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية للنظام', 1, 3, NULL, 1, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب كتابة اسم الاختراع وذلك طبقاً لأحكام المادة العاشرة الفقرة الأولى من اللائحة التنفيذية للنظام', 'يجب كتابة اسم الاختراع وذلك طبقاً لأحكام المادة العاشرة الفقرة الأولى من اللائحة التنفيذية للنظام', true, 'يجب كتابة اسم الاختراع وذلك طبقاً لأحكام المادة العاشرة الفقرة الأولى من اللائحة التنفيذية للنظام', 'يجب كتابة اسم الاختراع وذلك طبقاً لأحكام المادة العاشرة الفقرة الأولى من اللائحة التنفيذية للنظام', 1, 3, NULL, 1, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن يتطابق اسم الاختراع مع الاسم المذكور في المواصفة وفي نموذج التقديم وذلك طبقاً لأحكام المادة التاسعة الفقرة الثالثة من اللائحة التنفيذية', 'يجب أن يتطابق اسم الاختراع مع الاسم المذكور في المواصفة وفي نموذج التقديم وذلك طبقاً لأحكام المادة التاسعة الفقرة الثالثة من اللائحة التنفيذية', true, 'يجب أن يتطابق اسم الاختراع مع الاسم المذكور في المواصفة وفي نموذج التقديم وذلك طبقاً لأحكام المادة التاسعة الفقرة الثالثة من اللائحة التنفيذية', 'يجب أن يتطابق اسم الاختراع مع الاسم المذكور في المواصفة وفي نموذج التقديم وذلك طبقاً لأحكام المادة التاسعة الفقرة الثالثة من اللائحة التنفيذية', 1, 3, NULL, 1, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن يكون اسم الاختراع مختصراً ومحدداً ويفضل ألا يزيد عن (7) كلمات وذلك طبقاً لأحكام المادة العاشرة الفقرة الأولى من اللائحة التنفيذية للنظام', 'يجب أن يكون اسم الاختراع مختصراً ومحدداً ويفضل ألا يزيد عن (7) كلمات وذلك طبقاً لأحكام المادة العاشرة الفقرة الأولى من اللائحة التنفيذية للنظام', true, 'يجب أن يكون اسم الاختراع مختصراً ومحدداً ويفضل ألا يزيد عن (7) كلمات وذلك طبقاً لأحكام المادة العاشرة الفقرة الأولى من اللائحة التنفيذية للنظام', 'يجب أن يكون اسم الاختراع مختصراً ومحدداً ويفضل ألا يزيد عن (7) كلمات وذلك طبقاً لأحكام المادة العاشرة الفقرة الأولى من اللائحة التنفيذية للنظام', 1, 3, NULL, 1, 'APPLICANT', NULL, 'FORMAL_EXAMINER');





--------------------------الملخص------------------------------------
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن يشار للشكل العام للاختراع بالملخص وذلك طبقاً لأحكام المادة الثالثة عشرة الفقرة الثانية من اللائحة التنفيذية', 'يجب أن يشار للشكل العام للاختراع بالملخص وذلك طبقاً لأحكام المادة الثالثة عشرة الفقرة الثانية من اللائحة التنفيذية', true, 'يجب أن يشار للشكل العام للاختراع بالملخص وذلك طبقاً لأحكام المادة الثالثة عشرة الفقرة الثانية من اللائحة التنفيذية', 'يجب أن يشار للشكل العام للاختراع بالملخص وذلك طبقاً لأحكام المادة الثالثة عشرة الفقرة الثانية من اللائحة التنفيذية', 1, 4, NULL, 2, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن لا يتجاوز الملخص أكثر من صفحة وذلك طبقاً لأحكام المادة الثالثة عشرة الفقرة الأولى من اللائحة التنفيذية', 'يجب أن لا يتجاوز الملخص أكثر من صفحة وذلك طبقاً لأحكام المادة الثالثة عشرة الفقرة الأولى من اللائحة التنفيذية', true, 'يجب أن لا يتجاوز الملخص أكثر من صفحة وذلك طبقاً لأحكام المادة الثالثة عشرة الفقرة الأولى من اللائحة التنفيذية', 'يجب أن لا يتجاوز الملخص أكثر من صفحة وذلك طبقاً لأحكام المادة الثالثة عشرة الفقرة الأولى من اللائحة التنفيذية', 1, 4, NULL, 2, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب تعبئة القالب بالطريقة الصحيحة في (أدخل العنوان باللغة العربية) وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية للنظام', 'يجب تعبئة القالب بالطريقة الصحيحة في (أدخل العنوان باللغة العربية) وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية للنظام', true, 'يجب تعبئة القالب بالطريقة الصحيحة في (أدخل العنوان باللغة العربية) وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية للنظام', 'يجب تعبئة القالب بالطريقة الصحيحة في (أدخل العنوان باللغة العربية) وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية للنظام', 1, 4, NULL, 2, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن لا يحتوي الملخص على صفحات فارغة', 'يجب أن لا يحتوي الملخص على صفحات فارغة', true, 'يجب أن لا يحتوي الملخص على صفحات فارغة', 'يجب أن لا يحتوي الملخص على صفحات فارغة', 1, 4, NULL, 2, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب ترقيم أسطر الملخص بالطريقة الصحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية للنظام', 'يجب ترقيم أسطر الملخص بالطريقة الصحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية للنظام', true, 'يجب ترقيم أسطر الملخص بالطريقة الصحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية للنظام', 'يجب ترقيم أسطر الملخص بالطريقة الصحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية للنظام', 1, 4, NULL, 2, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب استخدام القالب الخاص بالملخص وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب استخدام القالب الخاص بالملخص وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', true, 'يجب استخدام القالب الخاص بالملخص وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب استخدام القالب الخاص بالملخص وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 1, 4, NULL, 2, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن يشار للشكل العام الصحيح للاختراع بالملخص وذلك طبقاً لأحكام المادة الثالثة عشرة الفقرة الثانية من اللائحة التنفيذية', 'يجب أن يشار للشكل العام الصحيح للاختراع بالملخص وذلك طبقاً لأحكام المادة الثالثة عشرة الفقرة الثانية من اللائحة التنفيذية', true, 'يجب أن يشار للشكل العام الصحيح للاختراع بالملخص وذلك طبقاً لأحكام المادة الثالثة عشرة الفقرة الثانية من اللائحة التنفيذية', 'يجب أن يشار للشكل العام الصحيح للاختراع بالملخص وذلك طبقاً لأحكام المادة الثالثة عشرة الفقرة الثانية من اللائحة التنفيذية', 1, 4, NULL, 2, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن يذكر في الملخص المجال التقني ووصف مختصر لأهم مكونات الاختراع واستعماله الرئيس وذلك طبقاً الثالثة عشرة الفقرة الرابعة من اللائحة التنفيذية', 'يجب أن يذكر في الملخص المجال التقني ووصف مختصر لأهم مكونات الاختراع واستعماله الرئيس وذلك طبقاً الثالثة عشرة الفقرة الرابعة من اللائحة التنفيذية', true, 'يجب أن يذكر في الملخص المجال التقني ووصف مختصر لأهم مكونات الاختراع واستعماله الرئيس وذلك طبقاً الثالثة عشرة الفقرة الرابعة من اللائحة التنفيذية', 'يجب أن يذكر في الملخص المجال التقني ووصف مختصر لأهم مكونات الاختراع واستعماله الرئيس وذلك طبقاً الثالثة عشرة الفقرة الرابعة من اللائحة التنفيذية', 1, 4, NULL, 2, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن يصاغ الملخص بأسلوب سهل يعطي فهماً واضحاً لحل المشكلة التقنية وذلك طبقاً الثالثة عشرة الفقرة الخامسة من اللائحة التنفيذية', 'يجب أن يصاغ الملخص بأسلوب سهل يعطي فهماً واضحاً لحل المشكلة التقنية وذلك طبقاً الثالثة عشرة الفقرة الخامسة من اللائحة التنفيذية', true, 'يجب أن يصاغ الملخص بأسلوب سهل يعطي فهماً واضحاً لحل المشكلة التقنية وذلك طبقاً الثالثة عشرة الفقرة الخامسة من اللائحة التنفيذية', 'يجب أن يصاغ الملخص بأسلوب سهل يعطي فهماً واضحاً لحل المشكلة التقنية وذلك طبقاً الثالثة عشرة الفقرة الخامسة من اللائحة التنفيذية', 1, 4, NULL, 2, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن يشار للشكل العام للاختراع بالملخص وذلك طبقاً لأحكام المادة الثالثة عشرة الفقرة الثانية من اللائحة التنفيذية', 'يجب أن يشار للشكل العام للاختراع بالملخص وذلك طبقاً لأحكام المادة الثالثة عشرة الفقرة الثانية من اللائحة التنفيذية', true, 'يجب أن يشار للشكل العام للاختراع بالملخص وذلك طبقاً لأحكام المادة الثالثة عشرة الفقرة الثانية من اللائحة التنفيذية', 'يجب أن يشار للشكل العام للاختراع بالملخص وذلك طبقاً لأحكام المادة الثالثة عشرة الفقرة الثانية من اللائحة التنفيذية', 1, 4, NULL, 2, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن يذكر اسم المصطلح العلمي بلغته الأصلية مرادفاً للاسم باللغة العربية عند وروده لأول مرة ويكتفى بالاسم العربي فقط في المرات اللاحقة وذلك طبقاً لأحكام المادة الثانية عشرة الفقرة الأولى من اللائحة التنفيذية', 'يجب أن يذكر اسم المصطلح العلمي بلغته الأصلية مرادفاً للاسم باللغة العربية عند وروده لأول مرة ويكتفى بالاسم العربي فقط في المرات اللاحقة وذلك طبقاً لأحكام المادة الثانية عشرة الفقرة الأولى من اللائحة التنفيذية', true, 'يجب أن يذكر اسم المصطلح العلمي بلغته الأصلية مرادفاً للاسم باللغة العربية عند وروده لأول مرة ويكتفى بالاسم العربي فقط في المرات اللاحقة وذلك طبقاً لأحكام المادة الثانية عشرة الفقرة الأولى من اللائحة التنفيذية', 'يجب أن يذكر اسم المصطلح العلمي بلغته الأصلية مرادفاً للاسم باللغة العربية عند وروده لأول مرة ويكتفى بالاسم العربي فقط في المرات اللاحقة وذلك طبقاً لأحكام المادة الثانية عشرة الفقرة الأولى من اللائحة التنفيذية', 1, 4, NULL, 2, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب استخدام نفس المصطلح المقابل باللغة العربية عند ورود كلمة لاتينية سبق إطلاق مصطلح مقابل لها باللغة العربية وذلك طبقاً لأحكام المادة الثانية عشرة الفقرة الثالثة من اللائحة التنفيذية', 'يجب استخدام نفس المصطلح المقابل باللغة العربية عند ورود كلمة لاتينية سبق إطلاق مصطلح مقابل لها باللغة العربية وذلك طبقاً لأحكام المادة الثانية عشرة الفقرة الثالثة من اللائحة التنفيذية', true, 'يجب استخدام نفس المصطلح المقابل باللغة العربية عند ورود كلمة لاتينية سبق إطلاق مصطلح مقابل لها باللغة العربية وذلك طبقاً لأحكام المادة الثانية عشرة الفقرة الثالثة من اللائحة التنفيذية', 'يجب استخدام نفس المصطلح المقابل باللغة العربية عند ورود كلمة لاتينية سبق إطلاق مصطلح مقابل لها باللغة العربية وذلك طبقاً لأحكام المادة الثانية عشرة الفقرة الثالثة من اللائحة التنفيذية', 1, 4, NULL, 2, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن يتطابق اسم الاختراع بالملخص مع نموذج التقديم (عربي/إنجليزي) وذلك طبقاً لأحكام المادة التاسعة الفقرة الثالثة من اللائحة التنفيذية', 'يجب أن يتطابق اسم الاختراع بالملخص مع نموذج التقديم (عربي/إنجليزي) وذلك طبقاً لأحكام المادة التاسعة الفقرة الثالثة من اللائحة التنفيذية', true, 'يجب أن يتطابق اسم الاختراع بالملخص مع نموذج التقديم (عربي/إنجليزي) وذلك طبقاً لأحكام المادة التاسعة الفقرة الثالثة من اللائحة التنفيذية', 'يجب أن يتطابق اسم الاختراع بالملخص مع نموذج التقديم (عربي/إنجليزي) وذلك طبقاً لأحكام المادة التاسعة الفقرة الثالثة من اللائحة التنفيذية', 1, 4, NULL, 2, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب تعبئة قالب الملخص بالطريقة الصحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب تعبئة قالب الملخص بالطريقة الصحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', true, 'يجب تعبئة قالب الملخص بالطريقة الصحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب تعبئة قالب الملخص بالطريقة الصحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 1, 4, NULL, 2, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب تصحيح الأخطاء الإملائية في اسم الاختراع بالملخص (عربي/إنجليزي) وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب تصحيح الأخطاء الإملائية في اسم الاختراع بالملخص (عربي/إنجليزي) وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', true, 'يجب تصحيح الأخطاء الإملائية في اسم الاختراع بالملخص (عربي/إنجليزي) وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب تصحيح الأخطاء الإملائية في اسم الاختراع بالملخص (عربي/إنجليزي) وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 1, 4, NULL, 2, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن يشار للشكل العام للاختراع بالملخص وذلك طبقاً لأحكام المادة الثالثة عشرة الفقرة الثانية من اللائحة التنفيذية', 'يجب إرفاق قالب الملخص في الخانة الصحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', true, 'يجب إرفاق قالب الملخص في الخانة الصحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب إرفاق قالب الملخص في الخانة الصحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 1, 4, NULL, 2, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن تشتمل المواصفة على الملخص وذلك طبقاً لأحكام المادة الحادية عشرة الفقرة الأولى من اللائحة التنفيذية', 'يجب أن تشتمل المواصفة على الملخص وذلك طبقاً لأحكام المادة الحادية عشرة الفقرة الأولى من اللائحة التنفيذية', true, 'يجب أن تشتمل المواصفة على الملخص وذلك طبقاً لأحكام المادة الحادية عشرة الفقرة الأولى من اللائحة التنفيذية', 'يجب أن تشتمل المواصفة على الملخص وذلك طبقاً لأحكام المادة الحادية عشرة الفقرة الأولى من اللائحة التنفيذية', 1, 4, NULL, 2, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن يكتب الملخص باللغة العربية وذلك طبقاً لأحكام المادة الثامنة الفقرة الأولى من اللائحة التنفيذية', 'يجب أن يكتب الملخص باللغة العربية وذلك طبقاً لأحكام المادة الثامنة الفقرة الأولى من اللائحة التنفيذية', true, 'يجب أن يكتب الملخص باللغة العربية وذلك طبقاً لأحكام المادة الثامنة الفقرة الأولى من اللائحة التنفيذية', 'يجب أن يكتب الملخص باللغة العربية وذلك طبقاً لأحكام المادة الثامنة الفقرة الأولى من اللائحة التنفيذية', 1, 4, NULL, 2, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب عدم إرفاق الرسومات التوضيحية ضمن الملخص وتضاف في خانة الرسومات التوضيحية وذلك طبقاً لأحكام المادة الحادية عشرة الفقرة الثالثة من اللائحة التنفيذية', 'يجب عدم إرفاق الرسومات التوضيحية ضمن الملخص وتضاف في خانة الرسومات التوضيحية وذلك طبقاً لأحكام المادة الحادية عشرة الفقرة الثالثة من اللائحة التنفيذية', true, 'يجب عدم إرفاق الرسومات التوضيحية ضمن الملخص وتضاف في خانة الرسومات التوضيحية وذلك طبقاً لأحكام المادة الحادية عشرة الفقرة الثالثة من اللائحة التنفيذية', 'يجب عدم إرفاق الرسومات التوضيحية ضمن الملخص وتضاف في خانة الرسومات التوضيحية وذلك طبقاً لأحكام المادة الحادية عشرة الفقرة الثالثة من اللائحة التنفيذية', 1, 4, NULL, 2, 'APPLICANT', NULL, 'FORMAL_EXAMINER');






-----------------------------الوصف الكامل----------------------------------
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن لا يحتوي الوصف الكامل على صفحات فارغة', 'يجب أن لا يحتوي الوصف الكامل على صفحات فارغة', true, 'يجب أن لا يحتوي الوصف الكامل على صفحات فارغة', 'يجب أن لا يحتوي الوصف الكامل على صفحات فارغة', 1, 4, NULL, 3, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب ترقيم أسطر الوصف الكامل بالطريقة الصحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب ترقيم أسطر الوصف الكامل بالطريقة الصحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', true, 'يجب ترقيم أسطر الوصف الكامل بالطريقة الصحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب ترقيم أسطر الوصف الكامل بالطريقة الصحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 1, 4, NULL, 3, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب استخدام القالب الخاص بالوصف الكامل وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب استخدام القالب الخاص بالوصف الكامل وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', true, 'يجب استخدام القالب الخاص بالوصف الكامل وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب استخدام القالب الخاص بالوصف الكامل وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 1, 4, NULL, 3, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن لا يحتوي الوصف الكامل على عناوين إضافية وذلك طبقاً لأحكام المادة الرابعة عشرة من اللائحة التنفيذية', 'يجب أن لا يحتوي الوصف الكامل على عناوين إضافية وذلك طبقاً لأحكام المادة الرابعة عشرة من اللائحة التنفيذية', true, 'يجب أن لا يحتوي الوصف الكامل على عناوين إضافية وذلك طبقاً لأحكام المادة الرابعة عشرة من اللائحة التنفيذية', 'يجب أن لا يحتوي الوصف الكامل على عناوين إضافية وذلك طبقاً لأحكام المادة الرابعة عشرة من اللائحة التنفيذية', 1, 4, NULL, 3, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن يذكر في شرح مختصر للرسومات شرحاً مختصراً للأشكال وقطاعاتها وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الثالثة من اللائحة التنفيذية', 'يجب أن يذكر في شرح مختصر للرسومات شرحاً مختصراً للأشكال وقطاعاتها وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الثالثة من اللائحة التنفيذية', true, 'يجب أن يذكر في شرح مختصر للرسومات شرحاً مختصراً للأشكال وقطاعاتها وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الثالثة من اللائحة التنفيذية', 'يجب أن يذكر في شرح مختصر للرسومات شرحاً مختصراً للأشكال وقطاعاتها وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الثالثة من اللائحة التنفيذية', 1, 4, NULL, 3, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن يذكر في خلفية الاختراع المجال التقني الذي يتناوله الاختراع ووصف حالة التقنية السابقة مع ذكر المشاكل التي تتعلق بالتقنية السابقة وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الأولى من اللائحة التنفيذية', 'يجب أن يذكر في خلفية الاختراع المجال التقني الذي يتناوله الاختراع ووصف حالة التقنية السابقة مع ذكر المشاكل التي تتعلق بالتقنية السابقة وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الأولى من اللائحة التنفيذية', true, 'يجب أن يذكر في خلفية الاختراع المجال التقني الذي يتناوله الاختراع ووصف حالة التقنية السابقة مع ذكر المشاكل التي تتعلق بالتقنية السابقة وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الأولى من اللائحة التنفيذية', 'يجب أن يذكر في خلفية الاختراع المجال التقني الذي يتناوله الاختراع ووصف حالة التقنية السابقة مع ذكر المشاكل التي تتعلق بالتقنية السابقة وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الأولى من اللائحة التنفيذية', 1, 4, NULL, 3, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن يذكر في الوصف العام للاختراع مزايا الاختراع مقارنة بحالة التقنية السابقة وكيفية التغلب على الصعوبات والمشاكل السابقة وكذلك الهدف من الاختراع وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الثانية من اللائحة التنفيذية', 'يجب أن يذكر في الوصف العام للاختراع مزايا الاختراع مقارنة بحالة التقنية السابقة وكيفية التغلب على الصعوبات والمشاكل السابقة وكذلك الهدف من الاختراع وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الثانية من اللائحة التنفيذية', true, 'يجب أن يذكر في الوصف العام للاختراع مزايا الاختراع مقارنة بحالة التقنية السابقة وكيفية التغلب على الصعوبات والمشاكل السابقة وكذلك الهدف من الاختراع وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الثانية من اللائحة التنفيذية', 'يجب أن يذكر في الوصف العام للاختراع مزايا الاختراع مقارنة بحالة التقنية السابقة وكيفية التغلب على الصعوبات والمشاكل السابقة وكذلك الهدف من الاختراع وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الثانية من اللائحة التنفيذية', 1, 4, NULL, 3, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن يذكر في الوصف التفصيلي وصفاً واضحاً وكافياً لتمكين رجل المهنة العادي من تنفيذ الاختراع وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الرابعة من اللائحة التنفيذية', 'يجب أن يذكر في الوصف التفصيلي وصفاً واضحاً وكافياً لتمكين رجل المهنة العادي من تنفيذ الاختراع وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الرابعة من اللائحة التنفيذية', true, 'يجب أن يذكر في الوصف التفصيلي وصفاً واضحاً وكافياً لتمكين رجل المهنة العادي من تنفيذ الاختراع وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الرابعة من اللائحة التنفيذية', 'يجب أن يذكر في الوصف التفصيلي وصفاً واضحاً وكافياً لتمكين رجل المهنة العادي من تنفيذ الاختراع وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الرابعة من اللائحة التنفيذية', 1, 4, NULL, 3, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن يذكر اسم المصطلح العلمي بلغته الأصلية مرادفاً للاسم باللغة العربية عند وروده لأول مرة ويكتفى بالاسم العربي فقط في المرات اللاحقة وذلك طبقاً لأحكام المادة الثانية عشرة الفقرة الأولى من اللائحة التنفيذية', 'يجب أن يذكر اسم المصطلح العلمي بلغته الأصلية مرادفاً للاسم باللغة العربية عند وروده لأول مرة ويكتفى بالاسم العربي فقط في المرات اللاحقة وذلك طبقاً لأحكام المادة الثانية عشرة الفقرة الأولى من اللائحة التنفيذية', true, 'يجب أن يذكر اسم المصطلح العلمي بلغته الأصلية مرادفاً للاسم باللغة العربية عند وروده لأول مرة ويكتفى بالاسم العربي فقط في المرات اللاحقة وذلك طبقاً لأحكام المادة الثانية عشرة الفقرة الأولى من اللائحة التنفيذية', 'يجب أن يذكر اسم المصطلح العلمي بلغته الأصلية مرادفاً للاسم باللغة العربية عند وروده لأول مرة ويكتفى بالاسم العربي فقط في المرات اللاحقة وذلك طبقاً لأحكام المادة الثانية عشرة الفقرة الأولى من اللائحة التنفيذية', 1, 4, NULL, 3, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب ذكر التسمية كاملة باللغة العربية والإنجليزية عند ورودها لأول مرة ويكتفى بعد ذلك بالتسمية المختصرة في الوصف الكامل وذلك طبقاً لأحكام المادة الثانية عشرة الفقرة الثانية من اللائحة التنفيذية', 'يجب ذكر التسمية كاملة باللغة العربية والإنجليزية عند ورودها لأول مرة ويكتفى بعد ذلك بالتسمية المختصرة في الوصف الكامل وذلك طبقاً لأحكام المادة الثانية عشرة الفقرة الثانية من اللائحة التنفيذية', true, 'يجب ذكر التسمية كاملة باللغة العربية والإنجليزية عند ورودها لأول مرة ويكتفى بعد ذلك بالتسمية المختصرة في الوصف الكامل وذلك طبقاً لأحكام المادة الثانية عشرة الفقرة الثانية من اللائحة التنفيذية', 'يجب ذكر التسمية كاملة باللغة العربية والإنجليزية عند ورودها لأول مرة ويكتفى بعد ذلك بالتسمية المختصرة في الوصف الكامل وذلك طبقاً لأحكام المادة الثانية عشرة الفقرة الثانية من اللائحة التنفيذية', 1, 4, NULL, 3, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب استخدام نفس المصطلح المقابل باللغة العربية عند ورود كلمة لاتينية سبق إطلاق مصطلح مقابل لها باللغة العربية وذلك طبقاً لأحكام المادة الثانية عشرة الفقرة الثالثة من اللائحة التنفيذية', 'يجب استخدام نفس المصطلح المقابل باللغة العربية عند ورود كلمة لاتينية سبق إطلاق مصطلح مقابل لها باللغة العربية وذلك طبقاً لأحكام المادة الثانية عشرة الفقرة الثالثة من اللائحة التنفيذية', true, 'يجب استخدام نفس المصطلح المقابل باللغة العربية عند ورود كلمة لاتينية سبق إطلاق مصطلح مقابل لها باللغة العربية وذلك طبقاً لأحكام المادة الثانية عشرة الفقرة الثالثة من اللائحة التنفيذية', 'يجب استخدام نفس المصطلح المقابل باللغة العربية عند ورود كلمة لاتينية سبق إطلاق مصطلح مقابل لها باللغة العربية وذلك طبقاً لأحكام المادة الثانية عشرة الفقرة الثالثة من اللائحة التنفيذية', 1, 4, NULL, 3, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن تكتب الرموز/الوحدات/التسميات/الثوابت الأساسية الفيزيائية بالطريقة التي أقرها الاتحاد الدولي للفيزياء البحثية والتطبيقية وذلك طبقاً لأحكام المادة الثانية عشرة الفقرة الرابعة من اللائحة التنفيذية', 'يجب أن تكتب الرموز/الوحدات/التسميات/الثوابت الأساسية الفيزيائية بالطريقة التي أقرها الاتحاد الدولي للفيزياء البحثية والتطبيقية وذلك طبقاً لأحكام المادة الثانية عشرة الفقرة الرابعة من اللائحة التنفيذية', true, 'يجب أن تكتب الرموز/الوحدات/التسميات/الثوابت الأساسية الفيزيائية بالطريقة التي أقرها الاتحاد الدولي للفيزياء البحثية والتطبيقية وذلك طبقاً لأحكام المادة الثانية عشرة الفقرة الرابعة من اللائحة التنفيذية', 'يجب أن تكتب الرموز/الوحدات/التسميات/الثوابت الأساسية الفيزيائية بالطريقة التي أقرها الاتحاد الدولي للفيزياء البحثية والتطبيقية وذلك طبقاً لأحكام المادة الثانية عشرة الفقرة الرابعة من اللائحة التنفيذية', 1, 4, NULL, 3, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن تكتب الأشكال البنائية /الصيغ الكيميائية/رموز العناصر/المركبات والأسماء الكيميائية بالأحرف اللاتينية حسب نظام IUPAC لكتابة الأشكال البنائية والصيغ الكيميائية ورموز العناصر والمركبات والأسماء الكيميائية وذلك طبقاً لأحكام المادة الثانية عشرة الفقرة الخامسة من اللائحة التنفيذية', 'يجب أن تكتب الأشكال البنائية /الصيغ الكيميائية/رموز العناصر/المركبات والأسماء الكيميائية بالأحرف اللاتينية حسب نظام IUPAC لكتابة الأشكال البنائية والصيغ الكيميائية ورموز العناصر والمركبات والأسماء الكيميائية وذلك طبقاً لأحكام المادة الثانية عشرة الفقرة الخامسة من اللائحة التنفيذية', true, 'يجب أن تكتب الأشكال البنائية /الصيغ الكيميائية/رموز العناصر/المركبات والأسماء الكيميائية بالأحرف اللاتينية حسب نظام IUPAC لكتابة الأشكال البنائية والصيغ الكيميائية ورموز العناصر والمركبات والأسماء الكيميائية وذلك طبقاً لأحكام المادة الثانية عشرة الفقرة الخامسة من اللائحة التنفيذية', 'يجب أن تكتب الأشكال البنائية /الصيغ الكيميائية/رموز العناصر/المركبات والأسماء الكيميائية بالأحرف اللاتينية حسب نظام IUPAC لكتابة الأشكال البنائية والصيغ الكيميائية ورموز العناصر والمركبات والأسماء الكيميائية وذلك طبقاً لأحكام المادة الثانية عشرة الفقرة الخامسة من اللائحة التنفيذية', 1, 4, NULL, 3, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب عدم إرفاق الرسومات التوضيحية ضمن الوصف الكامل وتضاف في خانة الرسومات التوضيحية وذلك طبقاً لأحكام المادة الحادية عشرة الفقرة الثالثة من اللائحة التنفيذية', 'يجب عدم إرفاق الرسومات التوضيحية ضمن الوصف الكامل وتضاف في خانة الرسومات التوضيحية وذلك طبقاً لأحكام المادة الحادية عشرة الفقرة الثالثة من اللائحة التنفيذية', true, 'يجب عدم إرفاق الرسومات التوضيحية ضمن الوصف الكامل وتضاف في خانة الرسومات التوضيحية وذلك طبقاً لأحكام المادة الحادية عشرة الفقرة الثالثة من اللائحة التنفيذية', 'يجب عدم إرفاق الرسومات التوضيحية ضمن الوصف الكامل وتضاف في خانة الرسومات التوضيحية وذلك طبقاً لأحكام المادة الحادية عشرة الفقرة الثالثة من اللائحة التنفيذية', 1, 4, NULL, 3, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن يتطابق اسم الاختراع بالوصف الكامل مع نموذج التقديم (عربي/إنجليزي) وذلك طبقاً لأحكام المادة التاسعة الفقرة الثالثة من اللائحة التنفيذية', 'يجب أن يتطابق اسم الاختراع بالوصف الكامل مع نموذج التقديم (عربي/إنجليزي) وذلك طبقاً لأحكام المادة التاسعة الفقرة الثالثة من اللائحة التنفيذية', true, 'يجب أن يتطابق اسم الاختراع بالوصف الكامل مع نموذج التقديم (عربي/إنجليزي) وذلك طبقاً لأحكام المادة التاسعة الفقرة الثالثة من اللائحة التنفيذية', 'يجب أن يتطابق اسم الاختراع بالوصف الكامل مع نموذج التقديم (عربي/إنجليزي) وذلك طبقاً لأحكام المادة التاسعة الفقرة الثالثة من اللائحة التنفيذية', 1, 4, NULL, 3, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'في حالة عدم وجود رسومات توضيحية تخص الطلب يجب أن يستخدم قالب الوصف الكامل الذي لا يحتوي على عنوان شرح مختصر للرسومات وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'في حالة عدم وجود رسومات توضيحية تخص الطلب يجب أن يستخدم قالب الوصف الكامل الذي لا يحتوي على عنوان شرح مختصر للرسومات وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', true, 'في حالة عدم وجود رسومات توضيحية تخص الطلب يجب أن يستخدم قالب الوصف الكامل الذي لا يحتوي على عنوان شرح مختصر للرسومات وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'في حالة عدم وجود رسومات توضيحية تخص الطلب يجب أن يستخدم قالب الوصف الكامل الذي لا يحتوي على عنوان شرح مختصر للرسومات وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 1, 4, NULL, 3, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب تعبئة قالب الوصف الكامل بالطريقة الصحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب تعبئة قالب الوصف الكامل بالطريقة الصحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', true, 'يجب تعبئة قالب الوصف الكامل بالطريقة الصحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب تعبئة قالب الوصف الكامل بالطريقة الصحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 1, 4, NULL, 3, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب تصحيح الأخطاء الإملائية في اسم الاختراع بالوصف الكامل (عربي/إنجليزي) وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب تصحيح الأخطاء الإملائية في اسم الاختراع بالوصف الكامل (عربي/إنجليزي) وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', true, 'يجب تصحيح الأخطاء الإملائية في اسم الاختراع بالوصف الكامل (عربي/إنجليزي) وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب تصحيح الأخطاء الإملائية في اسم الاختراع بالوصف الكامل (عربي/إنجليزي) وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 1, 4, NULL, 3, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن تذكر وثائق التقنية السابقة في خلفية الاختراع باللغة العربية وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الأولى من اللائحة التنفيذية', 'يجب أن تذكر وثائق التقنية السابقة في خلفية الاختراع باللغة العربية وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الأولى من اللائحة التنفيذية', true, 'يجب أن تذكر وثائق التقنية السابقة في خلفية الاختراع باللغة العربية وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الأولى من اللائحة التنفيذية', 'يجب أن تذكر وثائق التقنية السابقة في خلفية الاختراع باللغة العربية وذلك طبقاً لأحكام المادة الرابعة عشرة الفقرة الأولى من اللائحة التنفيذية', 1, 4, NULL, 3, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب إرفاق قالب الوصف الكامل في الخانة الصحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب إرفاق قالب الوصف الكامل في الخانة الصحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', true, 'يجب إرفاق قالب الوصف الكامل في الخانة الصحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب إرفاق قالب الوصف الكامل في الخانة الصحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 1, 4, NULL, 3, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن يكتب الوصف الكامل باللغة العربية وترفق الترجمة (إن وجدت) في المكان المخصص لها وذلك طبقاً لأحكام المادة الثامنة الفقرة الأولى من اللائحة التنفيذية', 'يجب أن يكتب الوصف الكامل باللغة العربية وترفق الترجمة (إن وجدت) في المكان المخصص لها وذلك طبقاً لأحكام المادة الثامنة الفقرة الأولى من اللائحة التنفيذية', true, 'يجب أن يكتب الوصف الكامل باللغة العربية وترفق الترجمة (إن وجدت) في المكان المخصص لها وذلك طبقاً لأحكام المادة الثامنة الفقرة الأولى من اللائحة التنفيذية', 'يجب أن يكتب الوصف الكامل باللغة العربية وترفق الترجمة (إن وجدت) في المكان المخصص لها وذلك طبقاً لأحكام المادة الثامنة الفقرة الأولى من اللائحة التنفيذية', 1, 4, NULL, 3, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب عدم ذكر عناصر الحماية ضمن الوصف الكامل وتضاف في خانة عناصر الحماية وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب عدم ذكر عناصر الحماية ضمن الوصف الكامل وتضاف في خانة عناصر الحماية وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', true, 'يجب عدم ذكر عناصر الحماية ضمن الوصف الكامل وتضاف في خانة عناصر الحماية وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب عدم ذكر عناصر الحماية ضمن الوصف الكامل وتضاف في خانة عناصر الحماية وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 1, 4, NULL, 3, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'في حالة وجود رسومات توضيحية تخص الطلب يجب أن يستخدم قالب الوصف الكامل الذي يحتوي على عنوان شرح مختصر للرسومات وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'في حالة وجود رسومات توضيحية تخص الطلب يجب أن يستخدم قالب الوصف الكامل الذي يحتوي على عنوان شرح مختصر للرسومات وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', true, 'في حالة وجود رسومات توضيحية تخص الطلب يجب أن يستخدم قالب الوصف الكامل الذي يحتوي على عنوان شرح مختصر للرسومات وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'في حالة وجود رسومات توضيحية تخص الطلب يجب أن يستخدم قالب الوصف الكامل الذي يحتوي على عنوان شرح مختصر للرسومات وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 1, 4, NULL, 3, 'APPLICANT', NULL, 'FORMAL_EXAMINER');

--------------------------------عناصر الحماية----------------------
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن يحتوي الطلب على عنصر حماية واحد مستقل على الأقل وذلك طبقاً لأحكام المادة الخامسة عشرة الفقرة الأولى من اللائحة التنفيذية', 'يجب أن يحتوي الطلب على عنصر حماية واحد مستقل على الأقل وذلك طبقاً لأحكام المادة الخامسة عشرة الفقرة الأولى من اللائحة التنفيذية', true, 'يجب أن يحتوي الطلب على عنصر حماية واحد مستقل على الأقل وذلك طبقاً لأحكام المادة الخامسة عشرة الفقرة الأولى من اللائحة التنفيذية', 'يجب أن يحتوي الطلب على عنصر حماية واحد مستقل على الأقل وذلك طبقاً لأحكام المادة الخامسة عشرة الفقرة الأولى من اللائحة التنفيذية', 1, 4, NULL, 4, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب ترقيم أسطر عناصر الحماية بالطريقة الصحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب ترقيم أسطر عناصر الحماية بالطريقة الصحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', true, 'يجب ترقيم أسطر عناصر الحماية بالطريقة الصحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب ترقيم أسطر عناصر الحماية بالطريقة الصحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 1, 4, NULL, 4, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن لا تحتوي عناصر الحماية على صفحات فارغة', 'يجب أن لا تحتوي عناصر الحماية على صفحات فارغة', true, 'يجب أن لا تحتوي عناصر الحماية على صفحات فارغة', 'يجب أن لا تحتوي عناصر الحماية على صفحات فارغة', 1, 4, NULL, 4, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب ترقيم عناصر الحماية بالتتابع وذلك طبقاً لأحكام المادة الخامسة عشرة الفقرة الأولى من اللائحة التنفيذية', 'يجب ترقيم عناصر الحماية بالتتابع وذلك طبقاً لأحكام المادة الخامسة عشرة الفقرة الأولى من اللائحة التنفيذية', true, 'يجب ترقيم عناصر الحماية بالتتابع وذلك طبقاً لأحكام المادة الخامسة عشرة الفقرة الأولى من اللائحة التنفيذية', 'يجب ترقيم عناصر الحماية بالتتابع وذلك طبقاً لأحكام المادة الخامسة عشرة الفقرة الأولى من اللائحة التنفيذية', 1, 4, NULL, 4, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب استخدام القالب الخاص بعناصر الحماية وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب استخدام القالب الخاص بعناصر الحماية وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', true, 'يجب استخدام القالب الخاص بعناصر الحماية وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب استخدام القالب الخاص بعناصر الحماية وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 1, 4, NULL, 4, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب تعبئة قالب عناصر الحماية بالطريقة الصحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب تعبئة قالب عناصر الحماية بالطريقة الصحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', true, 'يجب تعبئة قالب عناصر الحماية بالطريقة الصحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب تعبئة قالب عناصر الحماية بالطريقة الصحيحة وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 1, 4, NULL, 4, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب عدم إرفاق الرسومات التوضيحية ضمن عناصر الحماية وتضاف في خانة الرسومات التوضيحية. وذلك طبقاً لأحكام المادة الحادية عشرالفقرة الثالثة من اللائحة التنفيذية', 'يجب عدم إرفاق الرسومات التوضيحية ضمن عناصر الحماية وتضاف في خانة الرسومات التوضيحية. وذلك طبقاً لأحكام المادة الحادية عشرالفقرة الثالثة من اللائحة التنفيذية', true, 'يجب عدم إرفاق الرسومات التوضيحية ضمن عناصر الحماية وتضاف في خانة الرسومات التوضيحية. وذلك طبقاً لأحكام المادة الحادية عشرالفقرة الثالثة من اللائحة التنفيذية', 'يجب عدم إرفاق الرسومات التوضيحية ضمن عناصر الحماية وتضاف في خانة الرسومات التوضيحية. وذلك طبقاً لأحكام المادة الحادية عشرالفقرة الثالثة من اللائحة التنفيذية', 1, 4, NULL, 4, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن تكتب عناصر الحماية باللغة العربية وترفق الترجمة (إن وجدت) في المكان المخصص لها وذلك طبقاً لأحكام المادة الثامنة الفقرة الأولى من اللائحة التنفيذية', 'يجب أن تكتب عناصر الحماية باللغة العربية وترفق الترجمة (إن وجدت) في المكان المخصص لها وذلك طبقاً لأحكام المادة الثامنة الفقرة الأولى من اللائحة التنفيذية', true, 'يجب أن تكتب عناصر الحماية باللغة العربية وترفق الترجمة (إن وجدت) في المكان المخصص لها وذلك طبقاً لأحكام المادة الثامنة الفقرة الأولى من اللائحة التنفيذية', 'يجب أن تكتب عناصر الحماية باللغة العربية وترفق الترجمة (إن وجدت) في المكان المخصص لها وذلك طبقاً لأحكام المادة الثامنة الفقرة الأولى من اللائحة التنفيذية', 1, 4, NULL, 4, 'APPLICANT', NULL, 'FORMAL_EXAMINER');

----------------------------الرسومات---------------------------
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن لا تكون الرسومات التوضيحية مظللة أو محتوية على خلفية وذلك طبقاً لأحكام المادة السادسة عشرة الفقرة الثالثة من اللائحة التنفيذية', 'يجب أن لا تكون الرسومات التوضيحية مظللة أو محتوية على خلفية وذلك طبقاً لأحكام المادة السادسة عشرة الفقرة الثالثة من اللائحة التنفيذية', true, 'يجب أن لا تكون الرسومات التوضيحية مظللة أو محتوية على خلفية وذلك طبقاً لأحكام المادة السادسة عشرة الفقرة الثالثة من اللائحة التنفيذية', 'يجب أن لا تكون الرسومات التوضيحية مظللة أو محتوية على خلفية وذلك طبقاً لأحكام المادة السادسة عشرة الفقرة الثالثة من اللائحة التنفيذية', 1, 4, NULL, 4, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن تكون الرسومات التوضيحية جيدة وواضحة وذلك طبقاً لأحكام المادة السادسة عشرة الفقرة الأولى من اللائحة التنفيذية', 'يجب أن تكون الرسومات التوضيحية جيدة وواضحة وذلك طبقاً لأحكام المادة السادسة عشرة الفقرة الأولى من اللائحة التنفيذية', true, 'يجب أن تكون الرسومات التوضيحية جيدة وواضحة وذلك طبقاً لأحكام المادة السادسة عشرة الفقرة الأولى من اللائحة التنفيذية', 'يجب أن تكون الرسومات التوضيحية جيدة وواضحة وذلك طبقاً لأحكام المادة السادسة عشرة الفقرة الأولى من اللائحة التنفيذية', 1, 4, NULL, 4, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن لا تحتوي الرسومات التوضيحية على كلمات وصفية وذلك طبقاً لأحكام المادة السادسة عشرة الفقرة الرابعة من اللائحة التنفيذية', 'يجب أن لا تحتوي الرسومات التوضيحية على كلمات وصفية وذلك طبقاً لأحكام المادة السادسة عشرة الفقرة الرابعة من اللائحة التنفيذية', true, 'يجب أن لا تحتوي الرسومات التوضيحية على كلمات وصفية وذلك طبقاً لأحكام المادة السادسة عشرة الفقرة الرابعة من اللائحة التنفيذية', 'يجب أن لا تحتوي الرسومات التوضيحية على كلمات وصفية وذلك طبقاً لأحكام المادة السادسة عشرة الفقرة الرابعة من اللائحة التنفيذية', 1, 4, NULL, 4, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن ترقم الأشكال بأرقام منفصلة بغض النظر عن رقم الصفحة وذلك طبقاً لأحكام المادة السادسة عشرة الفقرة الثالثة من اللائحة التنفيذية', 'يجب أن ترقم الأشكال بأرقام منفصلة بغض النظر عن رقم الصفحة وذلك طبقاً لأحكام المادة السادسة عشرة الفقرة الثالثة من اللائحة التنفيذية', true, 'يجب أن ترقم الأشكال بأرقام منفصلة بغض النظر عن رقم الصفحة وذلك طبقاً لأحكام المادة السادسة عشرة الفقرة الثالثة من اللائحة التنفيذية', 'يجب أن ترقم الأشكال بأرقام منفصلة بغض النظر عن رقم الصفحة وذلك طبقاً لأحكام المادة السادسة عشرة الفقرة الثالثة من اللائحة التنفيذية', 1, 4, NULL, 4, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن لا تحتوي الرسومات التوضيحية على صفحات فارغة', 'يجب أن لا تحتوي الرسومات التوضيحية على صفحات فارغة', true, 'يجب أن لا تحتوي الرسومات التوضيحية على صفحات فارغة', 'يجب أن لا تحتوي الرسومات التوضيحية على صفحات فارغة', 1, 4, NULL, 4, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب ان تكون الرسومات التوضيحية عند الإرفاق مرتبة بتتابع أرقامها طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب ان تكون الرسومات التوضيحية عند الإرفاق مرتبة بتتابع أرقامها طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', true, 'يجب ان تكون الرسومات التوضيحية عند الإرفاق مرتبة بتتابع أرقامها طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب ان تكون الرسومات التوضيحية عند الإرفاق مرتبة بتتابع أرقامها طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 1, 4, NULL, 4, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب ترقيم الرسومات التوضيحية باللغة العربية طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب ترقيم الرسومات التوضيحية باللغة العربية طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', true, 'يجب ترقيم الرسومات التوضيحية باللغة العربية طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب ترقيم الرسومات التوضيحية باللغة العربية طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 1, 4, NULL, 4, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب إرفاق جميع الرسومات التوضيحية', 'يجب إرفاق جميع الرسومات التوضيحية', true, 'يجب إرفاق جميع الرسومات التوضيحية', 'يجب إرفاق جميع الرسومات التوضيحية', 1, 4, NULL, 4, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب عدم تكرار إرفاق الرسومات التوضيحية وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب عدم تكرار إرفاق الرسومات التوضيحية وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', true, 'يجب عدم تكرار إرفاق الرسومات التوضيحية وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب عدم تكرار إرفاق الرسومات التوضيحية وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 1, 4, NULL, 4, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن تكون الجداول ضمن الوصف الكامل للمواصفة وذلك طبقاً لأحكام المادة الحادية عشر الفقرة الثالثة من اللائحة التنفيذية', 'يجب أن تكون الجداول ضمن الوصف الكامل للمواصفة وذلك طبقاً لأحكام المادة الحادية عشر الفقرة الثالثة من اللائحة التنفيذية', true, 'يجب أن تكون الجداول ضمن الوصف الكامل للمواصفة وذلك طبقاً لأحكام المادة الحادية عشر الفقرة الثالثة من اللائحة التنفيذية', 'يجب أن تكون الجداول ضمن الوصف الكامل للمواصفة وذلك طبقاً لأحكام المادة الحادية عشر الفقرة الثالثة من اللائحة التنفيذية', 1, 4, NULL, 4, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب ان يكون الشكل الرئيسي مستقلاً وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب ان يكون الشكل الرئيسي مستقلاً وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', true, 'يجب ان يكون الشكل الرئيسي مستقلاً وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب ان يكون الشكل الرئيسي مستقلاً وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 1, 4, NULL, 4, 'APPLICANT', NULL, 'FORMAL_EXAMINER');

-------------------------بيانات المخترع -------------------------
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب إرفاق التنازل لجميع المخترعين وذلك طبقاً لأحكام المادة العاشرة الفقرة الثانية من اللائحة التنفيذية للنظام من النظام', 'يجب إرفاق التنازل لجميع المخترعين وذلك طبقاً لأحكام المادة العاشرة الفقرة الثانية من اللائحة التنفيذية للنظام من النظام', true, 'يجب إرفاق التنازل لجميع المخترعين وذلك طبقاً لأحكام المادة العاشرة الفقرة الثانية من اللائحة التنفيذية للنظام من النظام', 'يجب إرفاق التنازل لجميع المخترعين وذلك طبقاً لأحكام المادة العاشرة الفقرة الثانية من اللائحة التنفيذية للنظام من النظام', 1, 2, NULL, 1, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن يحتوي التنازل على اسم الاختراع وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية للنظام', 'يجب أن يحتوي التنازل على اسم الاختراع وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية للنظام', true, 'يجب أن يحتوي التنازل على اسم الاختراع وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية للنظام', 'يجب أن يحتوي التنازل على اسم الاختراع وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية للنظام', 1, 2, NULL, 1, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'التنازل المرفق لا يخص الطلب.', 'التنازل المرفق لا يخص الطلب.', true, 'التنازل المرفق لا يخص الطلب.', 'التنازل المرفق لا يخص الطلب.', 1, 2, NULL, 1, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن يتم توقيع جميع المخترعين وذلك طبقاً لأحكام المادة السادسة عشرة من النظام', 'يجب أن يتم توقيع جميع المخترعين وذلك طبقاً لأحكام المادة السادسة عشرة من النظام', true, 'يجب أن يتم توقيع جميع المخترعين وذلك طبقاً لأحكام المادة السادسة عشرة من النظام', 'يجب أن يتم توقيع جميع المخترعين وذلك طبقاً لأحكام المادة السادسة عشرة من النظام', 1, 2, NULL, 1, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن يكون التنازل معتمد وذلك طبقاً لأحكام المادة السادسة عشرة من النظام', 'يجب أن يكون التنازل معتمد وذلك طبقاً لأحكام المادة السادسة عشرة من النظام', true, 'يجب أن يكون التنازل معتمد وذلك طبقاً لأحكام المادة السادسة عشرة من النظام', 'يجب أن يكون التنازل معتمد وذلك طبقاً لأحكام المادة السادسة عشرة من النظام', 1, 2, NULL, 1, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب كتابة اسم المخترع وذلك طبقاً لأحكام المادة العاشرة الفقرة الثالثة من اللائحة التنفيذية للنظام', 'يجب كتابة اسم المخترع وذلك طبقاً لأحكام المادة العاشرة الفقرة الثالثة من اللائحة التنفيذية للنظام', true, 'يجب كتابة اسم المخترع وذلك طبقاً لأحكام المادة العاشرة الفقرة الثالثة من اللائحة التنفيذية للنظام', 'يجب كتابة اسم المخترع وذلك طبقاً لأحكام المادة العاشرة الفقرة الثالثة من اللائحة التنفيذية للنظام', 1, 2, NULL, 1, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن يكون اسم المخترع مطابق لما هو موجود في الهوية الوطنية وذلك طبقاً لأحكام المادة العاشرة الفقرة الثالثة من اللائحة التنفيذية للنظام', 'يجب أن يكون اسم المخترع مطابق لما هو موجود في الهوية الوطنية وذلك طبقاً لأحكام المادة العاشرة الفقرة الثالثة من اللائحة التنفيذية للنظام', true, 'يجب أن يكون اسم المخترع مطابق لما هو موجود في الهوية الوطنية وذلك طبقاً لأحكام المادة العاشرة الفقرة الثالثة من اللائحة التنفيذية للنظام', 'يجب أن يكون اسم المخترع مطابق لما هو موجود في الهوية الوطنية وذلك طبقاً لأحكام المادة العاشرة الفقرة الثالثة من اللائحة التنفيذية للنظام', 1, 2, NULL, 1, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب إرفاق التنازل وذلك طبقاً لأحكام المادة العاشرة الفقرة الثانية من اللائحة التنفيذية للنظام من النظام', 'يجب إرفاق التنازل وذلك طبقاً لأحكام المادة العاشرة الفقرة الثانية من اللائحة التنفيذية للنظام من النظام', true, 'يجب إرفاق التنازل وذلك طبقاً لأحكام المادة العاشرة الفقرة الثانية من اللائحة التنفيذية للنظام من النظام', 'يجب إرفاق التنازل وذلك طبقاً لأحكام المادة العاشرة الفقرة الثانية من اللائحة التنفيذية للنظام من النظام', 1, 2, NULL, 1, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب عدم تكرار اسم المخترع وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية للنظام', 'يجب عدم تكرار اسم المخترع وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية للنظام', true, 'يجب عدم تكرار اسم المخترع وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية للنظام', 'يجب عدم تكرار اسم المخترع وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية للنظام', 1, 2, NULL, 1, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن يكون مستند التنازل واضح وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب أن يكون مستند التنازل واضح وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', true, 'يجب أن يكون مستند التنازل واضح وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب أن يكون مستند التنازل واضح وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 1, 2, NULL, 1, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن تكون جميع البيانات الخاصة بالمخترع/المخترعين صحيحة وذلك طبقاً لأحكام المادة العاشرة الفقرة الثالثة من اللائحة التنفيذية', 'يجب أن تكون جميع البيانات الخاصة بالمخترع/المخترعين صحيحة وذلك طبقاً لأحكام المادة العاشرة الفقرة الثالثة من اللائحة التنفيذية', true, 'يجب أن تكون جميع البيانات الخاصة بالمخترع/المخترعين صحيحة وذلك طبقاً لأحكام المادة العاشرة الفقرة الثالثة من اللائحة التنفيذية', 'يجب أن تكون جميع البيانات الخاصة بالمخترع/المخترعين صحيحة وذلك طبقاً لأحكام المادة العاشرة الفقرة الثالثة من اللائحة التنفيذية', 1, 2, NULL, 1, 'APPLICANT', NULL, 'FORMAL_EXAMINER');

------------------------بيانات مقدم الطلب ----------------------------
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن يكون اسم مقدم/مقدمي الطلب مطابق لما هو موجود في التوكيل', 'يجب أن يكون اسم مقدم/مقدمي الطلب مطابق لما هو موجود في التوكيل', true, 'يجب أن يكون اسم مقدم/مقدمي الطلب مطابق لما هو موجود في التوكيل', 'يجب أن يكون اسم مقدم/مقدمي الطلب مطابق لما هو موجود في التوكيل', 1, 1, NULL, 1, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب كتابة اسم مقدم الطلب وذلك طبقاً لأحكام المادة العاشرة الفقرة الثانية من اللائحة التنفيذية', 'يجب كتابة اسم مقدم الطلب وذلك طبقاً لأحكام المادة العاشرة الفقرة الثانية من اللائحة التنفيذية', true, 'يجب كتابة اسم مقدم الطلب وذلك طبقاً لأحكام المادة العاشرة الفقرة الثانية من اللائحة التنفيذية', 'يجب كتابة اسم مقدم الطلب وذلك طبقاً لأحكام المادة العاشرة الفقرة الثانية من اللائحة التنفيذية', 1, 1, NULL, 1, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن تكون جميع البيانات الخاصة بمقدم/مقدمي الطلب مطابقة للوثائق الرسمية وذلك طبقاً لأحكام المادة العاشرة الفقرة الثانية من اللائحة التنفيذية', 'يجب أن تكون جميع البيانات الخاصة بمقدم/مقدمي الطلب مطابقة للوثائق الرسمية وذلك طبقاً لأحكام المادة العاشرة الفقرة الثانية من اللائحة التنفيذية', true, 'يجب أن تكون جميع البيانات الخاصة بمقدم/مقدمي الطلب مطابقة للوثائق الرسمية وذلك طبقاً لأحكام المادة العاشرة الفقرة الثانية من اللائحة التنفيذية', 'يجب أن تكون جميع البيانات الخاصة بمقدم/مقدمي الطلب مطابقة للوثائق الرسمية وذلك طبقاً لأحكام المادة العاشرة الفقرة الثانية من اللائحة التنفيذية', 1, 1, NULL, 1, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب إرفاق تصريح مزاولة أنشطة الملكية الفكرية الصادر من الهيئة السعودية للملكية الفكرية وذلك طبقاً لأحكام المادة العاشرة الفقرة السادسة من اللائحة التنفيذية', 'يجب إرفاق تصريح مزاولة أنشطة الملكية الفكرية الصادر من الهيئة السعودية للملكية الفكرية وذلك طبقاً لأحكام المادة العاشرة الفقرة السادسة من اللائحة التنفيذية', true, 'يجب إرفاق تصريح مزاولة أنشطة الملكية الفكرية الصادر من الهيئة السعودية للملكية الفكرية وذلك طبقاً لأحكام المادة العاشرة الفقرة السادسة من اللائحة التنفيذية', 'يجب إرفاق تصريح مزاولة أنشطة الملكية الفكرية الصادر من الهيئة السعودية للملكية الفكرية وذلك طبقاً لأحكام المادة العاشرة الفقرة السادسة من اللائحة التنفيذية', 1, 1, NULL, 1, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب إرفاق تصريح مزاولة المهنة ساري المفعول وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب إرفاق تصريح مزاولة المهنة ساري المفعول وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', true, 'يجب إرفاق تصريح مزاولة المهنة ساري المفعول وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 'يجب إرفاق تصريح مزاولة المهنة ساري المفعول وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية', 1, 1, NULL, 1, 'APPLICANT', NULL, 'FORMAL_EXAMINER');




