INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب إرفاق التوكيل الرسمي وذلك طبقاً لأحكام المادة السادسة عشرة من النظام', 'يجب إرفاق التوكيل الرسمي وذلك طبقاً لأحكام المادة السادسة عشرة من النظام', true, 'يجب إرفاق التوكيل الرسمي وذلك طبقاً لأحكام المادة السادسة عشرة من النظام', 'يجب إرفاق التوكيل الرسمي وذلك طبقاً لأحكام المادة السادسة عشرة من النظام', 1, 1, NULL, 1, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب إرفاق التوكيل لجميع مقدمي الطلب وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية للنظام', 'يجب إرفاق التوكيل لجميع مقدمي الطلب وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية للنظام', true, 'يجب إرفاق التوكيل لجميع مقدمي الطلب وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية للنظام', 'يجب إرفاق التوكيل لجميع مقدمي الطلب وذلك طبقاً لأحكام المادة التاسعة الفقرة السادسة من اللائحة التنفيذية للنظام', 1, 1, NULL, 1, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'التوكيل المرفق لا يخص الطلب ويجب إرفاق التوكيل الصحيح.', 'التوكيل المرفق لا يخص الطلب ويجب إرفاق التوكيل الصحيح.', true, 'التوكيل المرفق لا يخص الطلب ويجب إرفاق التوكيل الصحيح.', 'التوكيل المرفق لا يخص الطلب ويجب إرفاق التوكيل الصحيح.', 1, 1, NULL, 1, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
INSERT INTO application.lk_notes
(id, created_by_user, created_date, modified_by_user, modified_date, is_deleted, code, description_ar, description_en, enabled, name_ar, name_en, category_id, section_id, step_id, attribute_id, notes_type_enum, note_category_id, notes_step)
VALUES((select max (id+1) from application.lk_notes), NULL, NULL, NULL, NULL, 0, NULL, 'يجب أن يكون التوكيل معتمد وذلك طبقاً لأحكام المادة العاشرة الفقرة السادسة من اللائحة التنفيذية للنظام', 'يجب أن يكون التوكيل معتمد وذلك طبقاً لأحكام المادة العاشرة الفقرة السادسة من اللائحة التنفيذية للنظام', true, 'يجب أن يكون التوكيل معتمد وذلك طبقاً لأحكام المادة العاشرة الفقرة السادسة من اللائحة التنفيذية للنظام', 'يجب أن يكون التوكيل معتمد وذلك طبقاً لأحكام المادة العاشرة الفقرة السادسة من اللائحة التنفيذية للنظام', 1, 1, NULL, 1, 'APPLICANT', NULL, 'FORMAL_EXAMINER');
