ALTER TABLE application.lk_certificate_types
ADD enabled BOOLEAN NOT NULL  DEFAULT TRUE;


UPDATE application.lk_certificate_types
SET enabled = FALSE
WHERE code in
('CERTIFIED_PRIORITY_COPY','PROOF_ISSUANCE_APPLICATION','SECRET_DESIGN_DOCUMENT','FINAL_SPECIFICATION_DOCUMENT','PROOF_FACTS_APPEAL');