-- Auto-generated SQL script #202407141950
UPDATE application.lk_notes
SET is_deleted=1
WHERE category_id = 2 ;


-- Auto-generated SQL script #202407141957
INSERT INTO application.lk_note_category (id,code,name_ar,name_en)
VALUES ((select max(id) + 1 from application.lk_note_category),'INDUSTRIAL_NAME','اسم النموذج الصناعي (نوع المنتج) ','Industrial model name (product type)');
INSERT INTO application.lk_note_category (id,code,name_ar,name_en)
VALUES ((select max(id) + 1 from application.lk_note_category),'INDUSTRIAL_DESCRIPTION','وصف النموذج الصناعي','Description of the industrial model');
INSERT INTO application.lk_note_category (id,code,name_ar,name_en)
VALUES ((select max(id) + 1 from application.lk_note_category),'INDUSTRIAL_DOCUMENT_DESCRIPTION','الملاحظات المستندات القانونية ','Legal documents notes');
INSERT INTO application.lk_note_category (id,code,name_ar,name_en)
VALUES ((select max(id) + 1 from application.lk_note_category),'INDUSTRIAL_FORMAL_NOTE','الملاحظات الشكلية لبيانات المصممين ','Formal notes of designers'' statements');
INSERT INTO application.lk_note_category (id,code,name_ar,name_en)
VALUES ((select max(id) + 1 from application.lk_note_category),'INDUSTRIAL_FORMAL_NOTE_ATTORNEY','الملاحظات الشكلية التوكيل ','Formal notes of power of attorney');


-- Auto-generated SQL script #202407142007
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:25:05.067',0,'مقدم الطلب فرد وليس شركة','The applicant is an individual, not a company',true,'مقدم الطلب فرد وليس شركة','The applicant is an individual, not a company',2,1,'EXAMINAR','FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:25:05.067',0,'الجنسية غير محددة ','Nationality not specified',true,'الجنسية غير محددة ','Nationality not specified',2,1,'EXAMINAR','FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:25:05.067',0,'يجب ذكر جميع بيانات مقدمي الطلب. ','All applicants'' data must be mentioned.',true,'يجب ذكر جميع بيانات مقدمي الطلب. ','All applicants'' data must be mentioned.',2,1,'EXAMINAR','FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:25:05.067',0,'يجب تحديد نوع مقدم الطلب بشكل صحيح (فرد او شركة). ','The type of applicant must be specified correctly (individual or company).',true,'يجب تحديد نوع مقدم الطلب بشكل صحيح (فرد او شركة). ','The type of applicant must be specified correctly (individual or company).',2,1,'EXAMINAR','FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:25:05.067',0,'يوجد خطأ في بيانات مقدم الطلب. ','There is an error in the applicant''s data.',true,'يوجد خطأ في بيانات مقدم الطلب. ','There is an error in the applicant''s data.',2,1,'EXAMINAR','FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:25:05.067',0,'يوجد تكرار في اسم مقدم الطلب. ','There is a repetition in the applicant''s name.',true,'يوجد تكرار في اسم مقدم الطلب. ','There is a repetition in the applicant''s name.',2,1,'EXAMINAR','FORMAL_EXAMINER');

-- Auto-generated SQL script #202407142013
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:25:05.067',0,'إذ أنه لم يستوفي المطلوب وفق ماورد في الاشعار ','As he did not fulfill what was required in the notice',true,'إذ أنه لم يستوفي المطلوب وفق ماورد في الاشعار ','As he did not fulfill what was required in the notice',2,10,'EXAMINAR','FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:25:05.067',0,'إذ أنه لا تنطبق عليه شروط المنح ','Because the grant conditions do not apply to him',true,'إذ أنه لا تنطبق عليه شروط المنح ','Because the grant conditions do not apply to him',2,10,'EXAMINAR','FORMAL_EXAMINER');



-- Auto-generated SQL script #202407142101
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'الصور والرسومات لا توضح جميع أجزاء المنتج ','Pictures and drawings do not show all parts of the product',true,'الصور والرسومات لا توضح جميع أجزاء المنتج ','Pictures and drawings do not show all parts of the product',2,7,'EXAMINAR','FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'يجب إرفاق صور ورسومات للنموذج الصناعي المطلوب حمايته. ','Pictures and drawings of the industrial model to be protected must be attached.',true,'يجب إرفاق صور ورسومات للنموذج الصناعي المطلوب حمايته. ','Pictures and drawings of the industrial model to be protected must be attached.',2,7,'EXAMINAR','FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'الصور والرسومات لا تخص النموذج الصناعي المطلوب حمايته. ','Pictures and drawings do not relate to the industrial model to be protected.',true,'الصور والرسومات لا تخص النموذج الصناعي المطلوب حمايته. ','Pictures and drawings do not relate to the industrial model to be protected.',2,7,'EXAMINAR','FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'الصور والرسومات المرفقة مع الطلب لا تتطابق مع ما هو مرفق بالأسبقية. ','The pictures and drawings attached to the application do not match what is attached to the priority.',true,'الصور والرسومات المرفقة مع الطلب لا تتطابق مع ما هو مرفق بالأسبقية. ','The pictures and drawings attached to the application do not match what is attached to the priority.',2,7,'EXAMINAR','FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'الطلب يحتوى على أكثر من نموذج صناعى. ','The application contains more than one industrial model.',true,'الطلب يحتوى على أكثر من نموذج صناعى. ','The application contains more than one industrial model.',2,7,'EXAMINAR','FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'خلفية الصور والرسومات غير واضحة ولا تبين السمات المميزة للنموذج الصناعي المطلوب حمايته.  ','The background of the pictures and drawings is not clear and does not show the distinctive features of the industrial model to be protected.',true,'خلفية الصور والرسومات غير واضحة ولا تبين السمات المميزة للنموذج الصناعي المطلوب حمايته.  ','The background of the pictures and drawings is not clear and does not show the distinctive features of the industrial model to be protected.',2,7,'EXAMINAR','FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'تحتوى الصور والرسومات على خطوط لا تتعلق بالنموذج الصناعي المطلوب حمايته. ','The images and drawings contain lines that are not related to the industrial model to be protected.',true,'تحتوى الصور والرسومات على خطوط لا تتعلق بالنموذج الصناعي المطلوب حمايته. ','The images and drawings contain lines that are not related to the industrial model to be protected.',2,7,'EXAMINAR','FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'تحتوى الصور والرسومات على مقاطع عرضية. ','Pictures and drawings contain cross sections.',true,'تحتوى الصور والرسومات على مقاطع عرضية. ','Pictures and drawings contain cross sections.',2,7,'EXAMINAR','FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'الصور والرسومات للنموذج الصناعي المطلوب حمايته يجب ألا تزيد عن سبعة اشكال.  ','Pictures and drawings of the industrial model to be protected must not exceed seven shapes.',true,'الصور والرسومات للنموذج الصناعي المطلوب حمايته يجب ألا تزيد عن سبعة اشكال.  ','Pictures and drawings of the industrial model to be protected must not exceed seven shapes.',2,7,'EXAMINAR','FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'يجب فصل كل الصور والرسومات في صفحة مستقلة. ','All images and graphics should be separated on a separate page.',true,'يجب فصل كل الصور والرسومات في صفحة مستقلة. ','All images and graphics should be separated on a separate page.',2,7,'EXAMINAR','FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'يجب إلغاء الترقيم للصور والرسومات. ','Images and graphics must be unnumbered.',true,'يجب إلغاء الترقيم للصور والرسومات. ','Images and graphics must be unnumbered.',2,7,'EXAMINAR','FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'لا ينطبق على الطلب المقدم تعريف النموذج الصناعي.  ','The submitted application does not apply to the definition of an industrial model.',true,'لا ينطبق على الطلب المقدم تعريف النموذج الصناعي.  ','The submitted application does not apply to the definition of an industrial model.',2,7,'EXAMINAR','FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'الصور والرسومات تحتوى على شعارات ','Pictures and graphics contain logos',true,'الصور والرسومات تحتوى على شعارات ','Pictures and graphics contain logos',2,7,'EXAMINAR','FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'يجب أن تكون الصور والرسومات واضحة وتبين المنتج في صورته النهائية بدون أن صور إضافية. ','Pictures and drawings must be clear and show the product in its final form without additional images.',true,'يجب أن تكون الصور والرسومات واضحة وتبين المنتج في صورته النهائية بدون أن صور إضافية. ','Pictures and drawings must be clear and show the product in its final form without additional images.',2,7,'EXAMINAR','FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'يجب أن تكون الصور والرسومات واضحة وتبين المنتج في صورته النهائية. ','Pictures and drawings must be clear and show the product in its final form.',true,'يجب أن تكون الصور والرسومات واضحة وتبين المنتج في صورته النهائية. ','Pictures and drawings must be clear and show the product in its final form.',2,7,'EXAMINAR','FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'يجب الغاء الإطارات حول الصور والرسومات المرفقة. ','Frames around attached photos and graphics must be removed.',true,'يجب الغاء الإطارات حول الصور والرسومات المرفقة. ','Frames around attached photos and graphics must be removed.',2,7,'EXAMINAR','FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'الطلب المودع مخالف لأحكام المادة الرابعة من نظام براءات الاختراع والتصميمات التخطيطية للدارات المتكاملة والأصناف النباتية والنماذج الصناعية. ','The filed application violates the provisions of Article Four of the Patents and Layout Designs System for Integrated Circuits, Plant Varieties, and Industrial Designs.',true,'الطلب المودع مخالف لأحكام المادة الرابعة من نظام براءات الاختراع والتصميمات التخطيطية للدارات المتكاملة والأصناف النباتية والنماذج الصناعية. ','The filed application violates the provisions of Article Four of the Patents and Layout Designs System for Integrated Circuits, Plant Varieties, and Industrial Designs.',2,7,'EXAMINAR','FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'النموذج الصناعي يتضمن أعلاما أو شعارات رسمية.  ','The industrial model includes official flags or emblems.',true,'النموذج الصناعي يتضمن أعلاما أو شعارات رسمية.  ','The industrial model includes official flags or emblems.',2,7,'EXAMINAR','FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'يحتوى تصميم النموذج الصناعي على صور متحركة.  ','The industrial model design contains animated images.',true,'يحتوى تصميم النموذج الصناعي على صور متحركة.  ','The industrial model design contains animated images.',2,7,'EXAMINAR','FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'جودة الصور والرسومات منخفضة. ','Low quality images and graphics.',true,'جودة الصور والرسومات منخفضة. ','Low quality images and graphics.',2,7,'EXAMINAR','FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'يجب ان لا تحتوى الصور والرسومات على ظل. ','Pictures and graphics must not contain shadows.',true,'يجب ان لا تحتوى الصور والرسومات على ظل. ','Pictures and graphics must not contain shadows.',2,7,'EXAMINAR','FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'إذا كان هناك أجزاء في النموذج الصناعي غير مطلوب حمايتها فترسم بخطوط متقطعة. ','If there are parts in the industrial model that are not required to be protected, they are drawn with dashed lines.',true,'إذا كان هناك أجزاء في النموذج الصناعي غير مطلوب حمايتها فترسم بخطوط متقطعة. ','If there are parts in the industrial model that are not required to be protected, they are drawn with dashed lines.',2,7,'EXAMINAR','FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'يجب ألا تحتوى الصور والرسومات على أي كلمات او رموز لغرض الوصف.  ','Pictures and drawings must not contain any words or symbols for the purpose of description.',true,'يجب ألا تحتوى الصور والرسومات على أي كلمات او رموز لغرض الوصف.  ','Pictures and drawings must not contain any words or symbols for the purpose of description.',2,7,'EXAMINAR','FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'يرجى وضع الصور والرسومات بشكل رأسي. ','Please place pictures and drawings vertically',true,'يرجى وضع الصور والرسومات بشكل رأسي. ','Please place pictures and drawings vertically',2,7,'EXAMINAR','FORMAL_EXAMINER');


-- Auto-generated SQL script #202407142144
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,note_category_id,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'يجب كتابة اسم النموذج الصناعي باللغتين العربية والإنجليزية. ','The name of the industrial model must be written in Arabic and English.',true,'يجب كتابة اسم النموذج الصناعي باللغتين العربية والإنجليزية. ','The name of the industrial model must be written in Arabic and English.',2,3,'EXAMINAR',(SELECT x.id FROM application.lk_note_category x where x.code = 'INDUSTRIAL_NAME'),'FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,note_category_id,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'اسم النموذج الصناعي يتضمن على أخطاء املائية.  ','The name of the industrial model contains misspellings.',true,'اسم النموذج الصناعي يتضمن على أخطاء املائية.  ','The name of the industrial model contains misspellings.',2,3,'EXAMINAR',(SELECT x.id FROM application.lk_note_category x where x.code = 'INDUSTRIAL_NAME'),'FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,note_category_id,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'اسم النموذج الصناعي لا يشير الى نوع المنتج التي يستخدم فيها النموذج الصناعي  ','The name of the industrial model does not indicate the type of product in which the industrial model is used',true,'اسم النموذج الصناعي لا يشير الى نوع المنتج التي يستخدم فيها النموذج الصناعي  ','The name of the industrial model does not indicate the type of product in which the industrial model is used',2,3,'EXAMINAR',(SELECT x.id FROM application.lk_note_category x where x.code = 'INDUSTRIAL_NAME'),'FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,note_category_id,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'يوجد اختلاف بين اسم النموذج الصناعي عن ما هو متنازل عنه في مستند التنازل ','There is a difference between the name of the industrial model and what is assigned in the assignment document',true,'يوجد اختلاف بين اسم النموذج الصناعي عن ما هو متنازل عنه في مستند التنازل ','There is a difference between the name of the industrial model and what is assigned in the assignment document',2,3,'EXAMINAR',(SELECT x.id FROM application.lk_note_category x where x.code = 'INDUSTRIAL_NAME'),'FORMAL_EXAMINER');



-- Auto-generated SQL script #202407142149
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,note_category_id,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'الوصف المقدم عن النموذج الصناعي لا يبين استخدامات التصميم  ','The description provided about the industrial model does not indicate the uses of the design',true,'الوصف المقدم عن النموذج الصناعي لا يبين استخدامات التصميم  ','The description provided about the industrial model does not indicate the uses of the design',2,3,'EXAMINAR',(SELECT x.id FROM application.lk_note_category x where x.code = 'INDUSTRIAL_DESCRIPTION'),'FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,note_category_id,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'الوصف المقدم لا يصف كل شكل )صورة أو رسمة( من الأشكال المرفقة مع الطلب  ','The description provided does not describe each form (picture or drawing) attached to the application',true,'الوصف المقدم لا يصف كل شكل )صورة أو رسمة( من الأشكال المرفقة مع الطلب  ','The description provided does not describe each form (picture or drawing) attached to the application',2,3,'EXAMINAR',(SELECT x.id FROM application.lk_note_category x where x.code = 'INDUSTRIAL_DESCRIPTION'),'FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,note_category_id,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'يجب إضافة وصف مختصر للنموذج الصناعي.  ','A brief description of the industrial model must be added.',true,'يجب إضافة وصف مختصر للنموذج الصناعي.  ','A brief description of the industrial model must be added.',2,3,'EXAMINAR',(SELECT x.id FROM application.lk_note_category x where x.code = 'INDUSTRIAL_DESCRIPTION'),'FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,note_category_id,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'يجب تقديم وصف لكل شكل (صورة أو رسمة( من الأشكال المرفقة مع الطلب ','A description of each form (photo or drawing) attached to the application must be provided',true,'يجب تقديم وصف لكل شكل (صورة أو رسمة( من الأشكال المرفقة مع الطلب ','A description of each form (photo or drawing) attached to the application must be provided',2,3,'EXAMINAR',(SELECT x.id FROM application.lk_note_category x where x.code = 'INDUSTRIAL_DESCRIPTION'),'FORMAL_EXAMINER');



-- Auto-generated SQL script #202407142152
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,note_category_id,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'الوصف المقدم عن النموذج الصناعي لا يبين استخدامات التصميم  ','The documents submitted have not been translated',true,'لم يتم ترجمة الوثائق المقدمة ','The documents submitted have not been translated',2,3,'EXAMINAR',(SELECT x.id FROM application.lk_note_category x where x.code = 'INDUSTRIAL_DOCUMENT_DESCRIPTION'),'FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,note_category_id,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'الأسبقية لا تخص الطلب ','The precedence is not related to the request',true,'الأسبقية لا تخص الطلب ','The precedence is not related to the request',2,3,'EXAMINAR',(SELECT x.id FROM application.lk_note_category x where x.code = 'INDUSTRIAL_DOCUMENT_DESCRIPTION'),'FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,note_category_id,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'لم يتم إرفاق مستند الأسبقية ','No precedence document is attached',true,'لم يتم إرفاق مستند الأسبقية ','No precedence document is attached',2,3,'EXAMINAR',(SELECT x.id FROM application.lk_note_category x where x.code = 'INDUSTRIAL_DOCUMENT_DESCRIPTION'),'FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,note_category_id,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'يتضمن الطلب على علامات تجارية يجب ارفاق ما يثبت ملكيتها. ','The application includes trademarks that must be accompanied by proof of ownership.',true,'يتضمن الطلب على علامات تجارية يجب ارفاق ما يثبت ملكيتها. ','The application includes trademarks that must be accompanied by proof of ownership.',2,3,'EXAMINAR',(SELECT x.id FROM application.lk_note_category x where x.code = 'INDUSTRIAL_DOCUMENT_DESCRIPTION'),'FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,note_category_id,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'لم يتم ارفاق السجل التجارى لمقدم الطلب. ','The applicant''s commercial register was not attached.',true,'لم يتم ارفاق السجل التجارى لمقدم الطلب. ','The applicant''s commercial register was not attached.',2,3,'EXAMINAR',(SELECT x.id FROM application.lk_note_category x where x.code = 'INDUSTRIAL_DOCUMENT_DESCRIPTION'),'FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,note_category_id,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'لم يتم ارفاق المستندات القانونية الإضافية للطلب. ','Additional legal documents are not attached to the application.',true,'لم يتم ارفاق المستندات القانونية الإضافية للطلب. ','A description of each form (photo or drawing) attached to the application must be provided',2,3,'EXAMINAR',(SELECT x.id FROM application.lk_note_category x where x.code = 'INDUSTRIAL_DOCUMENT_DESCRIPTION'),'FORMAL_EXAMINER');




-- Auto-generated SQL script #202407142158
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,note_category_id,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'يجب ارفاق التنازل لجميع المصممين. ','A waiver must be attached to all designers.',true,'يجب ارفاق التنازل لجميع المصممين. ','A waiver must be attached to all designers.',2,2,'EXAMINAR',(SELECT x.id FROM application.lk_note_category x where x.code = 'INDUSTRIAL_FORMAL_NOTE'),'FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,note_category_id,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'التنازل المرفق لا يحتوى على اسم التصميم.  ','The attached waiver does not contain the name of the design.',true,'التنازل المرفق لا يحتوى على اسم التصميم.  ','The attached waiver does not contain the name of the design.',2,2,'EXAMINAR',(SELECT x.id FROM application.lk_note_category x where x.code = 'INDUSTRIAL_FORMAL_NOTE'),'FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,note_category_id,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'التنازل المرفق لا يخص الطلب. ','The attached waiver does not pertain to the application.',true,'التنازل المرفق لا يخص الطلب. ','The attached waiver does not pertain to the application.',2,2,'EXAMINAR',(SELECT x.id FROM application.lk_note_category x where x.code = 'INDUSTRIAL_FORMAL_NOTE'),'FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,note_category_id,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'التنازل المرفق غير مصدق عليه من الجهات ذات الاختصاص. ','The attached waiver has not been certified by the competent authorities.',true,'التنازل المرفق غير مصدق عليه من الجهات ذات الاختصاص. ','The attached waiver has not been certified by the competent authorities.',2,2,'EXAMINAR',(SELECT x.id FROM application.lk_note_category x where x.code = 'INDUSTRIAL_FORMAL_NOTE'),'FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,note_category_id,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'التنازل المرفق غير واضح. ','The attached waiver is not clear.',true,'التنازل المرفق غير واضح. ','The attached waiver is not clear.',2,2,'EXAMINAR',(SELECT x.id FROM application.lk_note_category x where x.code = 'INDUSTRIAL_FORMAL_NOTE'),'FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,note_category_id,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'يوجد اختلاف بين اسم التصميم المتنازل عنه وعن اسم التصميم بالطلب. ','There is a difference between the name of the assigned design and the name of the design in the application.',true,'يوجد اختلاف بين اسم التصميم المتنازل عنه وعن اسم التصميم بالطلب. ','There is a difference between the name of the assigned design and the name of the design in the application.',2,2,'EXAMINAR',(SELECT x.id FROM application.lk_note_category x where x.code = 'INDUSTRIAL_FORMAL_NOTE'),'FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,note_category_id,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'يوجد خطأ في اسم المصمم. ','There is an error in the designer''s name.',true,'يوجد خطأ في اسم المصمم. ','There is an error in the designer''s name.',2,2,'EXAMINAR',(SELECT x.id FROM application.lk_note_category x where x.code = 'INDUSTRIAL_FORMAL_NOTE'),'FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,note_category_id,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'يجب ان يكون المصمم شخص طبيعي ','The designer must be a natural person',true,'يجب ان يكون المصمم شخص طبيعي ','The designer must be a natural person',2,2,'EXAMINAR',(SELECT x.id FROM application.lk_note_category x where x.code = 'INDUSTRIAL_FORMAL_NOTE'),'FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,note_category_id,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'لا يوجد تطابق بين اسم المصمم بالطلب واسم المصمم بالتنازل. ','There is no match between the name of the designer on the order and the name of the designer on assignment.',true,'لا يوجد تطابق بين اسم المصمم بالطلب واسم المصمم بالتنازل. ','There is no match between the name of the designer on the order and the name of the designer on assignment.',2,2,'EXAMINAR',(SELECT x.id FROM application.lk_note_category x where x.code = 'INDUSTRIAL_FORMAL_NOTE'),'FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,note_category_id,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'يوجد شطب على بعض البيانات بوثيقة التنازل. ','There is a deletion of some data in the waiver document.',true,'يوجد شطب على بعض البيانات بوثيقة التنازل. ','There is a deletion of some data in the waiver document.',2,2,'EXAMINAR',(SELECT x.id FROM application.lk_note_category x where x.code = 'INDUSTRIAL_FORMAL_NOTE'),'FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,note_category_id,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'التنازل المرفق لا يحتوى على جميع أسماء المصممين. ','The attached disclaimer does not contain all the names of the designers.',true,'التنازل المرفق لا يحتوى على جميع أسماء المصممين. ','The attached disclaimer does not contain all the names of the designers.',2,2,'EXAMINAR',(SELECT x.id FROM application.lk_note_category x where x.code = 'INDUSTRIAL_FORMAL_NOTE'),'FORMAL_EXAMINER');





-- Auto-generated SQL script #202407142202
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,note_category_id,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'التوكيل المرفق لايخص الطلب ','The attached power of attorney is not specific to the request',true,'التوكيل المرفق لايخص الطلب ','The attached power of attorney is not specific to the request',2,2,'EXAMINAR',(SELECT x.id FROM application.lk_note_category x where x.code = 'INDUSTRIAL_FORMAL_NOTE_ATTORNEY'),'FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,note_category_id,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'لم يتم تعبئة جميع بيانات الوكيل ','Not all proxy data has been filled out',true,'لم يتم تعبئة جميع بيانات الوكيل ','Not all proxy data has been filled out',2,2,'EXAMINAR',(SELECT x.id FROM application.lk_note_category x where x.code = 'INDUSTRIAL_FORMAL_NOTE_ATTORNEY'),'FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,note_category_id,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'اسم مقدم الطلب يختلف عن الاسم الموجود في التوكيل ','The applicant''s name is different from the name on the power of attorney',true,'اسم مقدم الطلب يختلف عن الاسم الموجود في التوكيل ','The applicant''s name is different from the name on the power of attorney',2,2,'EXAMINAR',(SELECT x.id FROM application.lk_note_category x where x.code = 'INDUSTRIAL_FORMAL_NOTE_ATTORNEY'),'FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,note_category_id,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'تصريح مزاولة المهنة غير مرفق ','A permit to practice the profession is not attached',true,'تصريح مزاولة المهنة غير مرفق ','A permit to practice the profession is not attached',2,2,'EXAMINAR',(SELECT x.id FROM application.lk_note_category x where x.code = 'INDUSTRIAL_FORMAL_NOTE_ATTORNEY'),'FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,note_category_id,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'تاريخ تصريح مزاولة المهنة منتهى الصلاحية ','The date of the permit to practice the profession has expired',true,'تاريخ تصريح مزاولة المهنة منتهى الصلاحية ','The date of the permit to practice the profession has expired',2,2,'EXAMINAR',(SELECT x.id FROM application.lk_note_category x where x.code = 'INDUSTRIAL_FORMAL_NOTE_ATTORNEY'),'FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,note_category_id,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'لم يتم إرفاق التوكيل الرسمي. ','The power of attorney is not attached.',true,'لم يتم إرفاق التوكيل الرسمي. ','The power of attorney is not attached.',2,2,'EXAMINAR',(SELECT x.id FROM application.lk_note_category x where x.code = 'INDUSTRIAL_FORMAL_NOTE_ATTORNEY'),'FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,note_category_id,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'لم يتم ارفاق التوكيل لجميع مقدمي الطلب. ','Power of attorney is not attached to all applicants.',true,'لم يتم ارفاق التوكيل لجميع مقدمي الطلب. ','Power of attorney is not attached to all applicants.',2,2,'EXAMINAR',(SELECT x.id FROM application.lk_note_category x where x.code = 'INDUSTRIAL_FORMAL_NOTE_ATTORNEY'),'FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,note_category_id,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'التوكيل المرفق غير مصدق عليه من الجهات ذات الاختصاص. ','The attached power of attorney has not been certified by the competent authorities.',true,'التوكيل المرفق غير مصدق عليه من الجهات ذات الاختصاص. ','The attached power of attorney has not been certified by the competent authorities.',2,2,'EXAMINAR',(SELECT x.id FROM application.lk_note_category x where x.code = 'INDUSTRIAL_FORMAL_NOTE_ATTORNEY'),'FORMAL_EXAMINER');
INSERT INTO application.lk_notes (id,created_by_user,created_date,is_deleted,description_ar,description_en,enabled,name_ar,name_en,category_id,section_id,notes_type_enum,note_category_id,notes_step)
VALUES ((select max(id) +1 from application.lk_notes),'adel.c','2024-07-14 15:30:07.181',0,'التوكيل المرفق غير واضح. ','The attached power of attorney is not clear.',true,'التوكيل المرفق غير واضح. ','The attached power of attorney is not clear.',2,2,'EXAMINAR',(SELECT x.id FROM application.lk_note_category x where x.code = 'INDUSTRIAL_FORMAL_NOTE_ATTORNEY'),'FORMAL_EXAMINER');






