package gov.saip.applicationservice.common.enums.certificate;

public enum CertificateTypeEnum {
    ISSUE_CERTIFICATE, CERTIFIED_REGISTER_COPY, CERTIFIED_PRIORITY_COPY, PROOF_ISSUANCE_APPLICATION, PROOF_FACTS_APPEAL,
    SECRET_DESIGN_DOCUMENT, FINAL_SPECIFICATION_DOCUMENT, ALL_APPLICATION_RECORDS, DEPOSIT_CERTIFICATE, REVOKE_VOLUNTARY_TRADEMARK_CERTIFICATE, EXACT_COPY,
    LICENSE_REGISTRATION_CERTIFICATE, LICENSE_CANCELLATION_CERTIFICATE, PATENT_ISSUE_CERTIFICATE, INTEGRATED_CIRCUITS_ISSUE_CERTIFICATE
}
