package gov.saip.applicationservice.common.enums;

public enum ApplicationUserRoleEnum {
    CHECKER, HEAD_OF_CHECKER, EXAMINER, HEAD_OF_EXAMINER, CLASSIFICATION_SPECIALIST, APPEAL_SPECIALIST
    ,THQQ_EMPLOYEE, EQM_MANAGER,EQM_EVALUATOR,EQM_EXPERT,
    ASSISTIVE_SERVICES_SPECIALIST, TM_AGENCY_CHECKER,PATENT_ACCELERATED_SPECIALIST,
    ASSISTIVE_SERVICES_RESEARCH_OFFICER_TM,
    PUBLICATION_SPECIALIST , PUBLICATION_AUDITOR,
    ASSISTIVE_SERVICES_AGENCIES_CHECKER,
    APPEAL_COORDINATOR,
    APPEAL_HEAD,
    APPEAL_MEMBER,
    OPPOSITION_SPECIALIST,
    TRADEMARK_EXAMINER,
    ASSISTIVE_SERVICES_PETITION_SPECIALIST_PT,
    ASSISTIVE_SERVICES_SPECIALIST_TM,
    ASSISTIVE_SERVICES_SPECIALIST_PT,
    ASSISTIVE_SERVICES_SPECIALIST_ID;
}
