package gov.saip.applicationservice.common.enums;

public enum ApplicationPaymentRequestTypesEnum {
    APPLICATION_UPDATE_2,
    APPLICATION_UPDATE_1,
    FILE_NEW_APPLICATION,
    WITHDRAW_APPLICATION,
    SUBSTANSIVE_EXAMINATION_FEE,
    PUBLICATION_FEE,
    CHANGE_AGENT_REQUEST,
    EXTEND_PERIOD_FORMAL_EXAMINATION,
    RELINQUISHMENT,
    PETITION_FOR_RECOVERY,
    PAPER_SHAPES,
    PAPER_CLAIMS,
    SUBS_UPDATE_1,
    SUBS_UPDATE_2,
    PAPER,
    ADD_APPLICANT_TO_APPLICATION,
    ADD_PPH_EXAMINATION,
    ADD_FAST_TRACK_EXAMINATION,
    ADD_ACCERLATED_EXAMINATION,
    INITIAL_UPDATE,
    LICENSING_REGISTRATION


}
