package gov.saip.applicationservice.common.enums;

public enum DocumentTypeEnum {
    POA,
    APPLICATION_XML,
    EDIT_TRADEMARK_IMAGE,
    INTEGRATED_CIRCUITS_FRONT_SHAPE_DOCUMENT,
    INTEGRATED_CIRCUITS_BACK_SHAPE_DOCUMENT,
    INTEGRATED_CIRCUITS_COMMERCIAL_EXPLOITATION_DOC,
    INTEGRATED_CIRCUITS_LEGAL_DOCUMENT,
    INTEGRATED_CIRCUITS_WAIVER_DOCUMENT,
    INTEGRATED_CIRCUITS_CHECKER_MODIFICATION_DOCUMENT,
    INTEGRATED_CIRCUITS_CHECKER_REJECTION_DOCUMENT,
    INTEGRATED_CIRCUITS_CHECKER_GRANT_DOCUMENT,
    INTEGRATED_CIRCUITS_GRANT_CERTIFICATE_DOCUMENT,
    INTEGRATED_CIRCUITS_MERGED_DOCUMENTS,
    MAIN_PHOTO_PLANT_VEGETARIAN,
    DUS_DOCUMENT_TESTING,
    VEGETARIAN_DOCUMENT_PERVIOUS_TEST,
    INTEGRATED_CIRCUITS_SECOND_CHECKER_MODIFICATION_DOCUMENT,
    INDUSTRIAL_DESIGN_CHECKER_REPORT ,
    INDUSTRIAL_DESIGN_SECOND_CHECKER_REPORT ,
    INDUSTRIAL_DESIGN_OBJECTION,
    INDUSTRIAL_DESIGN_FEE_GRANT,
    PLANT_VARIETIES_CHECKER_MODIFICATION_DOCUMENT,
    PLANT_VARIETIES_CHECKER_REJECTION_DOCUMENT,
    PLANT_VARIETIES_CHECKER_GRANT_DOCUMENT,
    PLANT_VARIETIES_SECOND_CHECKER_MODIFICATION_DOCUMENT
    ;
}
