package gov.saip.applicationservice.common.enums;

public enum PublicationType {

    LICENCE_CANCELLATION,
    TRADEMARK_RENEWAL,
    TRADEMARK_LICENCE_USE,
    TRADEMARK_REGISTERATION,
    TRADEMARK_PICTURE_EDIT,
    OWNERORADDRESS_EDIT,
    TRADEMARK_PLEDGE,
    COURT_DELETION_ORDER,
    VOLUNTARY_TRADEMARK_DELETION,
    UNLOCK_TRADEMARK,
    PRODUCTS_LIMIT,
    OWNERSHIP_TRANSFER,
    PATENT_REGISTRATION,
    INDUSTRIAL_DESIGN_REGISTRATION,
    
    AGENT_SUBSTITUTION,
    INDUSTRIAL_DESIGN_LICENCE_USE,
    PATENT_LICENCE_USE,
    PATENT_PRODUCTS_LIMIT,
    PATENT_COURT_DELETION_ORDER,
    VOLUNTARY_PATENT_DELETION,
    INDUSTRIAL_DESIGN_PRODUCTS_LIMIT,
    INDUSTRIAL_DESIGN_COURT_DELETION_ORDER,
    VOLUNTARY_INDUSTRIAL_DESIGN_DELETION,
    EDIT_NAME_OR_ADDRESS,
    EDIT_TRADEMARK_IMAGE,
    NONE,
    LICENCE_REVOKE,
    INDUSTRIAL_DESIGN_RENEWAL,PUBLICATION_A

    
    
    
}
