package gov.saip.applicationservice.common.enums;

public enum RequestActivityLogEnum {
    EVICTION, RETRACTION, ANNUAL_FEES_PAY, OPPOSITION_COMPLETED, PETITION_REQUEST_NATIONAL_STAGE, EXTENSION, APPLICATION_ACCELERATED_REQUEST, TRADEMARK_APPLICATION_WAIVED, RENEWAL_APPLICATION_DESERTION;
}
