package gov.saip.applicationservice.common.enums;

public enum RequestTypeEnum {
    FOREIGN_REG,
    ORG_REG,
    USER_REG,

    TRADEMARK,
    INDUSTRIAL_DESIGN,
    PATENT,
    INTEGRATED_CIRCUITS,
    PLANT_VARIETIES,

    TRADEMARK_AGENCY_REQUEST,

    TRADEMARK_OWNER,
    LEGAL_REPRESENTITVE,
    SUSPICIOUS_CASE,
    COMPLAIN_REQUEST,
    INVESTIGATION_REQUEST,
    ITEM_SUSPICIOUS_CASE_REQUEST,
    MULTI,
    SINGLE,


    EQM_REQUEST,

    APPEAL_REQUEST,
    OPPOSITION_REQUEST,
    EXTENSION_REQUEST,
    AGENT_SUBSTITUTION_REQUEST,
    CHANGE_OWNERSHIP,
    LICENSING_REGISTRATION,
    PROTECTION_PERIOD_EXTENSION_REQUEST,
    VOLUNTARY_REVOKE,
    REVOKE_BY_COURT_ORDER,
    REVOKE_PRODUCTS,
    TRADEMARK_APPLICATION_SEARCH,
    EDIT_TRADEMARK_NAME_ADDRESS,
    REVOKE_LICENSE_REQUEST,
    TRADEMARK_APPEAL_REQUEST,
    EDIT_TRADEMARK_IMAGE,
    PETITION_REQUEST_NATIONAL_STAGE,
    PETITION_RECOVERY,
    PATENT_PRIORITY_REQUEST,
    PATENT_PRIORITY_MODIFY,

    EXAMINER_CONSULTATION,
    EVICTION,
    LICENSING_MODIFICATION,
    EXTENSION
    ;
}
