package gov.saip.applicationservice.common.enums;

public enum SupportedServiceCode {
    ADD_AGENT,
    SUBSTITUTE_AGENT,
    DELETE_AGENT,
    APPEAL_REQUEST,
    SPECIFICATION_MODIFICATION,
    TITLE_MODIFICATION,
    PATENT_PRIORITY_MODIFY,
    PATENT_PRIORITY_REQUEST,
    WITHDRAW_APPLICATION_IF_PENDING,
    WITHDRAW_APPLICATION_UNLESS_FINAL_ACTION_ISSUED_BY_EXAMINERS_OFFICE;
}
