package gov.saip.applicationservice.common.enums;

import gov.saip.applicationservice.common.model.LKSupportServiceRequestStatus;
import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum SupportServiceRequestStatusEnum {
    DRAFT,
    UNDER_PROCEDURE,
    REQUEST_CORRECTION,
    APPROVED,
    REJECTED,
    COMPLETED,
    OPPOSITION_WATING,
    LICENSE_REVOKED,
    UNDER_OPPOSITION,
    WITHDRAWAL,
    PENDING,
    PENDING_IMG_FEES_MOD_REQ,
    UNDER_REVIEW_VISUAL,
    UNDER_REVIEW_SUBJECTIVE,
    UNDER_REVIEW_AUDITOR,
    ACCEPTED_WITH_MOD,
    ACCEPTED_MOD_REQUEST,
    PENDING_IMG_FEES_MOD_PUB,
    PUBLISHED_ELECTRONIC,
    TRADEMARK_IMAGE_MODIFIED,
    REJECTED_BY_MANAGEMENT,
    WAIVED,
    PENDING_FEES_COMPLAINT,
    COMPLAINANT_TO_COMMITTEE,
    ACCEPTED_BY_COMMITTEE,
    LICENSED,
    RENEWED,
    TRADMARK_REVOKED,
    DENIED_AGENCY,
    TRANSFERRED_OWNERSHIP,
    REJECTED_BY_APPEAL_COMMITTEE,
    APPEAL_RETURNED_TO_DEPARTMENT,
    COURT_DOCUMENTS_CORRECTION,
    HAVE_SIMILAR,
    NOT_SIMILAR,
    CONDITIONAL_REJECTION,
    REOPENED,
    PETITION_RECOVERY_REJECTION,
    PETITION_RECOVERY_APPROVAL,
    PAY_PUBLICATION_FEES,
    PENDING_RENEWAL_FEES,
    ACCEPTED,
    APPEAL_REQUEST_CORRECTION,
    ACCEPTED_AGENCY_REQUEST,
    AGENT_DELETION_APPROVED,
    DROPOUT
    ;

}
